INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('atha', 'giannisj3@mail.com', '56f6daafa5ccac0bb043d6692323f968', '1999-10-20', 'John-Atha', 'John', 'Athanasiou');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Harry.Co', 'Harry66@mail.com', 'f2c34463841431d0da5feb99156414d7', '1982-09-14', 'Harry-Coo', 'Harry', 'Cooper');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Thaleia.Mccl', 'Thaleia2@mail.com', 'febcb7099436edeecac73c58eecdb5f8', '2000-02-09', 'Thaleia-Mccl', 'Thaleia', 'Mcclure');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Antony_Mc', 'Antony56@yahoo.com', '448f771128827b71e4ab4b57297229af', '1984-07-11', 'Antony-Mccl', 'Antony', 'Mcclure');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Peter.Mo', 'Peter44@windowslive.com', 'f831327fae122f450bfb4b76b6fd5a2b', '1990-06-07', 'Peter-Mo', 'Peter', 'Morse');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Nantia.Bla', 'Nantia62@windowslive.com', 'f6125ed4d1c7e9049b6a10c556ace17b', '1983-06-06', 'Nantia-Blac', 'Nantia', 'Blackwell');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('George_Mye', 'George80@yahoo.com', '94a50ce3e7793152cac5341bccf1a455', '1995-03-21', 'George-My', 'George', 'Myers');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Antony_Wo', 'Antony5@yahoo.com', 'f877f2e36dd0299fc84c42ec3814be51', '1983-09-26', 'Antony-Wo', 'Antony', 'Woods');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Panagiotis_Ingr', 'Panagiotis97@mail.com', '46fe00352fe2e47bec478d9d33943941', '1988-04-08', 'Panagiotis-In', 'Panagiotis', 'Ingram');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Dora_Zamo', 'Dora63@gmail.com', '8f5f9d0a3c9fc25a47d0e8b608e97cac', '1995-02-08', 'Dora-Zamo', 'Dora', 'Zamora');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Spyros_Fau', 'Spyros28@yahoo.com', '70bfcbf0a59543ef1d154d95fcb14ac1', '1997-11-17', 'Spyros-Fa', 'Spyros', 'Faulkner');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Penelope_Coo', 'Penelope72@windowslive.com', '534e9563646f007beb4da977c31aba0b', '1981-05-26', 'Penelope-Coo', 'Penelope', 'Cooper');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Nantia_Ki', 'Nantia83@windowslive.com', '7ba3e35bdf78d7eae83614acf568cd13', '1986-06-08', 'Nantia-Kir', 'Nantia', 'Kirk');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Leonidas.Be', 'Leonidas16@yahoo.com', 'ae4c138f38857a48dc9cb88249ffbd01', '1988-12-10', 'Leonidas-Be', 'Leonidas', 'Benitez');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Steve.Mcc', 'Steve55@yahoo.com', 'c487447a5c27bdaf7dd0345a089476cf', '1995-12-22', 'Steve-Mccl', 'Steve', 'Mcclure');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Andrew_Co', 'Andrew78@yahoo.com', '741b97448c2e5636ef9f6c7422d09955', '1992-12-17', 'Andrew-Coop', 'Andrew', 'Cooper');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Peter.Ingr', 'Peter50@mail.com', '354ff67604d754ac711622e65ab60449', '1984-08-15', 'Peter-Ing', 'Peter', 'Ingram');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Nantia_Ben', 'Nantia5@gmail.com', '2f8e5c7b9707fc10a82b5c9d802f64a8', '1990-05-25', 'Nantia-Beni', 'Nantia', 'Benitez');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Steve.All', 'Steve25@yahoo.com', 'e8ee8521a103d1e3276223f07daa4757', '1985-11-23', 'Steve-All', 'Steve', 'Allen');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Leonidas_Zam', 'Leonidas27@yahoo.com', '073d834be7f074235f1f88aad147ee97', '1996-04-08', 'Leonidas-Zamo', 'Leonidas', 'Zamora');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Antony_Za', 'Antony48@gmail.com', 'fed278dea96affc91fa4fcfd4c31d896', '1994-03-17', 'Antony-Zam', 'Antony', 'Zamora');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Thanos_Murp', 'Thanos90@mail.com', 'db53b13f74946390382c642fc8781314', '1995-11-27', 'Thanos-Mu', 'Thanos', 'Murphy');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Leonidas.Pru', 'Leonidas45@gmail.com', '7e289cc812cb15adb2c8f25e41b68f51', '1980-07-22', 'Leonidas-Pru', 'Leonidas', 'Pruitt');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Stamatis.Sim', 'Stamatis41@mail.com', 'f5b25c55b39d2f9971a0192478fc8f08', '1997-05-17', 'Stamatis-Si', 'Stamatis', 'Simon');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Nantia_Ho', 'Nantia34@mail.com', 'cb495349010395714db68eb216adc78d', '1984-11-08', 'Nantia-Hog', 'Nantia', 'Hogan');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Thanos_Zam', 'Thanos45@yahoo.com', 'c94b373462c2b4f7bf613600512201f8', '1990-11-25', 'Thanos-Zamo', 'Thanos', 'Zamora');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Leonidas_Bla', 'Leonidas83@yahoo.com', '7af2f3eee9c9421d193aef103c5675d1', '1999-08-26', 'Leonidas-Blac', 'Leonidas', 'Blackwell');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Harry_Bla', 'Harry44@windowslive.com', 'f8e367b16f3b35cc25817b68ce4de20a', '2000-06-13', 'Harry-Blac', 'Harry', 'Blackwell');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Dimitris_Schm', 'Dimitris56@mail.com', 'd3b957257fd6294210788103bc740063', '1986-04-26', 'Dimitris-Sc', 'Dimitris', 'Schmitt');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Dimitris.All', 'Dimitris66@windowslive.com', '601cdb8e7cdd424dbf1f7329076f01f6', '1997-11-27', 'Dimitris-Alle', 'Dimitris', 'Allen');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Peter.Bo', 'Peter38@gmail.com', 'f5ff4395a8d018bb3c83cb6499dd90ba', '1980-07-19', 'Peter-Boye', 'Peter', 'Boyer');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('George.He', 'George71@mail.com', 'e7f624f7c2f7afbbb66454fb773f673a', '1983-08-22', 'George-He', 'George', 'Henderson');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Thanos_Mcc', 'Thanos68@gmail.com', '14bc4f0969138856b3eb7fa16d80f0bd', '1991-04-12', 'Thanos-Mccl', 'Thanos', 'Mcclure');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Steve_Mor', 'Steve37@yahoo.com', 'd3415db183ed074af35dd29029cb65e9', '1998-12-10', 'Steve-Mors', 'Steve', 'Morse');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Antony.Si', 'Antony19@mail.com', 'd06c1e8587a8e0a2fc175b0b7c734fd1', '1985-06-07', 'Antony-Sim', 'Antony', 'Simon');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('George.Ma', 'George30@mail.com', '1a6b145169dc4aeb911e1387c36151a1', '1985-06-13', 'George-Maxw', 'George', 'Maxwell');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Dimitris.Mull', 'Dimitris24@mail.com', '596750fa8057a01ee2ec9c32d6fc250b', '1983-01-06', 'Dimitris-Mul', 'Dimitris', 'Mullen');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Panagiotis.Ben', 'Panagiotis39@mail.com', 'd6a25cb3bab6af66e7730f2706536a70', '1993-05-25', 'Panagiotis-Ben', 'Panagiotis', 'Benitez');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Nantia_Kirk', 'Nantia97@yahoo.com', '4dec7aa7a798497a3ef94f33a4fe850b', '1984-06-28', 'Nantia-Kir', 'Nantia', 'Kirk');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Thanos.Ing', 'Thanos52@windowslive.com', '8787efcf271fb67fbd2d0188fb2f9cd7', '1981-10-18', 'Thanos-Ingr', 'Thanos', 'Ingram');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Dimitris_Co', 'Dimitris94@mail.com', 'c47be224afedf53af6451b47af59a16e', '2000-09-22', 'Dimitris-Co', 'Dimitris', 'Cooper');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Emily.Ma', 'Emily96@gmail.com', '486edf92591282bcb09a97fc98ab6310', '1987-11-08', 'Emily-Maye', 'Emily', 'Mayer');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Dimitris_He', 'Dimitris12@windowslive.com', 'c11d5ee71501f88ae22533ee704605a8', '1988-02-16', 'Dimitris-Hen', 'Dimitris', 'Henderson');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Kyriakh.My', 'Kyriakh16@yahoo.com', '2e5812b43d4458abf32a2d5c4bee0097', '1985-02-21', 'Kyriakh-Mye', 'Kyriakh', 'Myers');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Thaleia.Mye', 'Thaleia21@gmail.com', 'ebb8f13d4170af64bfab65a6c5365b5f', '2001-06-18', 'Thaleia-Mye', 'Thaleia', 'Myers');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Kyriakh.Are', 'Kyriakh67@gmail.com', 'f8f4fc64b6479d40cf4d0b9f2e679a92', '1994-09-11', 'Kyriakh-Ar', 'Kyriakh', 'Arellano');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Leonidas_Hen', 'Leonidas78@yahoo.com', '12867324403bf638053ad1c0a2ce799e', '1985-06-25', 'Leonidas-Hend', 'Leonidas', 'Henderson');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('John_Coo', 'John86@gmail.com', '024396f6efaaac76f45db988a2cbfed7', '1995-12-01', 'John-Co', 'John', 'Cooper');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Antony_Huf', 'Antony14@windowslive.com', '4a8c50e9a62155b435735afb9a5ec997', '1989-11-01', 'Antony-Hu', 'Antony', 'Huff');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Kyriakh_Huf', 'Kyriakh94@windowslive.com', 'cc005b5bf0f240a68371f72a76f6a695', '1981-08-21', 'Kyriakh-Huff', 'Kyriakh', 'Huff');
INSERT INTO public."User"(username, email, password, date_of_birth, github_username, first_name, last_name) VALUES('Dimitris_Mul', 'Dimitris16@yahoo.com', '61847fa206035bdcec83b8477699f007', '1990-07-24', 'Dimitris-Mull', 'Dimitris', 'Mullen');

INSERT INTO public."keyword"(name) VALUES('Django');
INSERT INTO public."keyword"(name) VALUES('Spring boot');
INSERT INTO public."keyword"(name) VALUES('Express js');
INSERT INTO public."keyword"(name) VALUES('Node js');
INSERT INTO public."keyword"(name) VALUES('Laravel');
INSERT INTO public."keyword"(name) VALUES('Python');
INSERT INTO public."keyword"(name) VALUES('c++');
INSERT INTO public."keyword"(name) VALUES('algorithms');
INSERT INTO public."keyword"(name) VALUES('data structures');
INSERT INTO public."keyword"(name) VALUES('sql');
INSERT INTO public."keyword"(name) VALUES('databases');
INSERT INTO public."keyword"(name) VALUES('postgres');
INSERT INTO public."keyword"(name) VALUES('heroku');
INSERT INTO public."keyword"(name) VALUES('vscode');
INSERT INTO public."keyword"(name) VALUES('webstormweb developing');
INSERT INTO public."keyword"(name) VALUES('html');
INSERT INTO public."keyword"(name) VALUES('css');
INSERT INTO public."keyword"(name) VALUES('vanilla js');
INSERT INTO public."keyword"(name) VALUES('react');
INSERT INTO public."keyword"(name) VALUES('angular');
INSERT INTO public."keyword"(name) VALUES('react-native');
INSERT INTO public."keyword"(name) VALUES('vue');
INSERT INTO public."keyword"(name) VALUES('flutter');
INSERT INTO public."keyword"(name) VALUES('selenium');
INSERT INTO public."keyword"(name) VALUES('ubuntu');
INSERT INTO public."keyword"(name) VALUES('linux');
INSERT INTO public."keyword"(name) VALUES('windows');

INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(1, 10);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(1, 23);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(2, 14);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(2, 24);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(3, 13);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(3, 25);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(4, 26);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(4, 5);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(5, 8);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(5, 3);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(6, 24);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(6, 4);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(7, 15);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(7, 6);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(8, 8);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(8, 6);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(9, 23);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(9, 15);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(10, 1);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(10, 10);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(11, 18);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(11, 17);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(12, 20);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(12, 26);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(13, 4);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(13, 22);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(14, 21);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(14, 15);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(15, 13);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(15, 8);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(16, 7);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(16, 10);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(17, 26);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(17, 12);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(18, 10);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(18, 15);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(19, 7);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(19, 2);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(20, 2);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(20, 22);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(21, 9);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(21, 17);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(22, 11);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(22, 15);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(23, 18);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(23, 3);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(24, 10);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(24, 22);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(25, 5);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(25, 22);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(26, 1);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(26, 4);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(27, 14);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(27, 12);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(28, 5);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(28, 15);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(29, 7);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(29, 9);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(30, 3);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(30, 17);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(31, 17);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(31, 3);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(32, 2);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(32, 18);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(33, 25);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(33, 17);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(34, 7);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(34, 9);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(35, 24);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(35, 13);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(36, 24);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(36, 11);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(37, 10);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(37, 13);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(38, 9);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(38, 7);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(39, 1);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(39, 17);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(40, 15);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(40, 4);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(41, 5);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(41, 8);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(42, 1);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(42, 11);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(43, 10);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(43, 13);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(44, 3);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(44, 25);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(45, 10);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(45, 17);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(46, 17);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(46, 7);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(47, 15);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(47, 14);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(48, 20);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(48, 1);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(49, 2);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(49, 3);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(50, 4);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(50, 14);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(51, 25);
INSERT INTO public."user_keyword"(user_id, keyword_id) VALUES(51, 24);

INSERT INTO public."question"(user_id, title, text, date) VALUES(13, 'insert in mysql', 'What is the fastest way to insert data in mysql?', '2021-03-18 16:45:16');
INSERT INTO public."question"(user_id, title, text, date) VALUES(31, 'insert in postgresql', 'What is the fastest way to insert data in postgresql?', '2021-04-28 20:41:35');
INSERT INTO public."question"(user_id, title, text, date) VALUES(37, 'insert in mongodb', 'What is the fastest way to insert data in mongodb?', '2021-02-27 06:41:15');
INSERT INTO public."question"(user_id, title, text, date) VALUES(50, 'insert in relational databases', 'What is the fastest way to insert data in relational databases?', '2021-01-02 22:12:18');
INSERT INTO public."question"(user_id, title, text, date) VALUES(38, 'insert in non-relational databases', 'What is the fastest way to insert data in non-relational databases?', '2021-03-24 18:43:55');
INSERT INTO public."question"(user_id, title, text, date) VALUES(1, 'insert in django', 'What is the fastest way to insert data in django?', '2021-03-10 21:44:22');
INSERT INTO public."question"(user_id, title, text, date) VALUES(47, 'insert in spring boot', 'What is the fastest way to insert data in spring boot?', '2020-10-20 00:18:53');
INSERT INTO public."question"(user_id, title, text, date) VALUES(19, 'insert in laravel', 'What is the fastest way to insert data in laravel?', '2021-03-23 22:47:02');
INSERT INTO public."question"(user_id, title, text, date) VALUES(25, 'delete in mysql', 'What is the fastest way to delete data in mysql?', '2020-07-20 01:40:26');
INSERT INTO public."question"(user_id, title, text, date) VALUES(44, 'delete in postgresql', 'What is the fastest way to delete data in postgresql?', '2021-02-04 01:35:14');
INSERT INTO public."question"(user_id, title, text, date) VALUES(35, 'delete in mongodb', 'What is the fastest way to delete data in mongodb?', '2020-08-16 20:50:29');
INSERT INTO public."question"(user_id, title, text, date) VALUES(32, 'delete in relational databases', 'What is the fastest way to delete data in relational databases?', '2020-12-15 23:07:18');
INSERT INTO public."question"(user_id, title, text, date) VALUES(36, 'delete in non-relational databases', 'What is the fastest way to delete data in non-relational databases?', '2021-05-11 05:08:45');
INSERT INTO public."question"(user_id, title, text, date) VALUES(3, 'delete in django', 'What is the fastest way to delete data in django?', '2020-07-08 20:00:48');
INSERT INTO public."question"(user_id, title, text, date) VALUES(38, 'delete in spring boot', 'What is the fastest way to delete data in spring boot?', '2021-03-08 10:16:18');
INSERT INTO public."question"(user_id, title, text, date) VALUES(25, 'delete in laravel', 'What is the fastest way to delete data in laravel?', '2021-04-09 06:04:58');
INSERT INTO public."question"(user_id, title, text, date) VALUES(39, 'update in mysql', 'What is the fastest way to update data in mysql?', '2021-03-13 08:26:17');
INSERT INTO public."question"(user_id, title, text, date) VALUES(9, 'update in postgresql', 'What is the fastest way to update data in postgresql?', '2021-05-16 15:41:02');
INSERT INTO public."question"(user_id, title, text, date) VALUES(1, 'update in mongodb', 'What is the fastest way to update data in mongodb?', '2021-01-16 09:50:11');
INSERT INTO public."question"(user_id, title, text, date) VALUES(11, 'update in relational databases', 'What is the fastest way to update data in relational databases?', '2021-01-20 20:17:36');
INSERT INTO public."question"(user_id, title, text, date) VALUES(10, 'update in non-relational databases', 'What is the fastest way to update data in non-relational databases?', '2021-01-03 08:51:11');
INSERT INTO public."question"(user_id, title, text, date) VALUES(27, 'update in django', 'What is the fastest way to update data in django?', '2020-06-20 17:09:29');
INSERT INTO public."question"(user_id, title, text, date) VALUES(7, 'update in spring boot', 'What is the fastest way to update data in spring boot?', '2021-03-05 11:15:16');
INSERT INTO public."question"(user_id, title, text, date) VALUES(19, 'update in laravel', 'What is the fastest way to update data in laravel?', '2021-02-10 13:54:43');
INSERT INTO public."question"(user_id, title, text, date) VALUES(4, 'read in mysql', 'What is the fastest way to read data in mysql?', '2021-03-05 08:19:10');
INSERT INTO public."question"(user_id, title, text, date) VALUES(48, 'read in postgresql', 'What is the fastest way to read data in postgresql?', '2021-05-23 15:43:25');
INSERT INTO public."question"(user_id, title, text, date) VALUES(26, 'read in mongodb', 'What is the fastest way to read data in mongodb?', '2021-02-04 23:01:04');
INSERT INTO public."question"(user_id, title, text, date) VALUES(15, 'read in relational databases', 'What is the fastest way to read data in relational databases?', '2021-05-27 04:29:46');
INSERT INTO public."question"(user_id, title, text, date) VALUES(37, 'read in non-relational databases', 'What is the fastest way to read data in non-relational databases?', '2021-02-18 12:35:16');
INSERT INTO public."question"(user_id, title, text, date) VALUES(20, 'read in django', 'What is the fastest way to read data in django?', '2021-03-20 07:05:16');
INSERT INTO public."question"(user_id, title, text, date) VALUES(34, 'read in spring boot', 'What is the fastest way to read data in spring boot?', '2020-10-16 08:44:27');
INSERT INTO public."question"(user_id, title, text, date) VALUES(7, 'read in laravel', 'What is the fastest way to read data in laravel?', '2021-05-26 17:42:10');
INSERT INTO public."question"(user_id, title, text, date) VALUES(39, 'an array in c++', 'How can I implement an array in c++?', '2021-04-13 23:37:13');
INSERT INTO public."question"(user_id, title, text, date) VALUES(4, 'an array in python', 'How can I implement an array in python?', '2021-04-12 10:03:10');
INSERT INTO public."question"(user_id, title, text, date) VALUES(4, 'an array in javascript', 'How can I implement an array in javascript?', '2021-01-10 12:49:53');
INSERT INTO public."question"(user_id, title, text, date) VALUES(11, 'an array in java', 'How can I implement an array in java?', '2021-03-22 05:00:12');
INSERT INTO public."question"(user_id, title, text, date) VALUES(44, 'an array in swipl', 'How can I implement an array in swipl?', '2021-01-17 10:45:09');
INSERT INTO public."question"(user_id, title, text, date) VALUES(37, 'a linked list in c++', 'How can I implement a linked list in c++?', '2020-06-24 10:00:31');
INSERT INTO public."question"(user_id, title, text, date) VALUES(48, 'a linked list in python', 'How can I implement a linked list in python?', '2021-03-10 12:09:22');
INSERT INTO public."question"(user_id, title, text, date) VALUES(18, 'a linked list in javascript', 'How can I implement a linked list in javascript?', '2021-05-23 05:57:17');
INSERT INTO public."question"(user_id, title, text, date) VALUES(17, 'a linked list in java', 'How can I implement a linked list in java?', '2021-01-08 06:17:48');
INSERT INTO public."question"(user_id, title, text, date) VALUES(37, 'a linked list in swipl', 'How can I implement a linked list in swipl?', '2021-05-14 23:34:01');
INSERT INTO public."question"(user_id, title, text, date) VALUES(41, 'a queue in c++', 'How can I implement a queue in c++?', '2021-04-28 00:14:33');
INSERT INTO public."question"(user_id, title, text, date) VALUES(24, 'a queue in python', 'How can I implement a queue in python?', '2020-01-13 17:33:23');
INSERT INTO public."question"(user_id, title, text, date) VALUES(1, 'a queue in javascript', 'How can I implement a queue in javascript?', '2020-04-07 11:15:13');
INSERT INTO public."question"(user_id, title, text, date) VALUES(24, 'a queue in java', 'How can I implement a queue in java?', '2020-01-08 20:59:26');
INSERT INTO public."question"(user_id, title, text, date) VALUES(15, 'a queue in swipl', 'How can I implement a queue in swipl?', '2020-11-15 10:56:43');
INSERT INTO public."question"(user_id, title, text, date) VALUES(15, 'a priority queue in c++', 'How can I implement a priority queue in c++?', '2021-04-08 18:48:00');
INSERT INTO public."question"(user_id, title, text, date) VALUES(46, 'a priority queue in python', 'How can I implement a priority queue in python?', '2021-04-06 07:35:23');
INSERT INTO public."question"(user_id, title, text, date) VALUES(21, 'a priority queue in javascript', 'How can I implement a priority queue in javascript?', '2021-05-13 10:25:15');
INSERT INTO public."question"(user_id, title, text, date) VALUES(40, 'a priority queue in java', 'How can I implement a priority queue in java?', '2021-03-21 21:38:09');
INSERT INTO public."question"(user_id, title, text, date) VALUES(49, 'a priority queue in swipl', 'How can I implement a priority queue in swipl?', '2020-02-01 00:59:05');
INSERT INTO public."question"(user_id, title, text, date) VALUES(35, 'a stack in c++', 'How can I implement a stack in c++?', '2021-01-03 14:21:55');
INSERT INTO public."question"(user_id, title, text, date) VALUES(34, 'a stack in python', 'How can I implement a stack in python?', '2020-06-22 08:48:09');
INSERT INTO public."question"(user_id, title, text, date) VALUES(37, 'a stack in javascript', 'How can I implement a stack in javascript?', '2021-02-02 21:44:54');
INSERT INTO public."question"(user_id, title, text, date) VALUES(3, 'a stack in java', 'How can I implement a stack in java?', '2020-10-14 03:01:18');
INSERT INTO public."question"(user_id, title, text, date) VALUES(35, 'a stack in swipl', 'How can I implement a stack in swipl?', '2021-01-07 02:27:17');
INSERT INTO public."question"(user_id, title, text, date) VALUES(26, 'a graph in c++', 'How can I implement a graph in c++?', '2021-05-25 11:39:57');
INSERT INTO public."question"(user_id, title, text, date) VALUES(24, 'a graph in python', 'How can I implement a graph in python?', '2021-02-15 21:40:25');
INSERT INTO public."question"(user_id, title, text, date) VALUES(13, 'a graph in javascript', 'How can I implement a graph in javascript?', '2021-02-06 17:18:03');
INSERT INTO public."question"(user_id, title, text, date) VALUES(22, 'a graph in java', 'How can I implement a graph in java?', '2021-04-26 13:30:20');
INSERT INTO public."question"(user_id, title, text, date) VALUES(38, 'a graph in swipl', 'How can I implement a graph in swipl?', '2021-04-25 05:00:41');
INSERT INTO public."question"(user_id, title, text, date) VALUES(39, 'a tree in c++', 'How can I implement a tree in c++?', '2021-04-05 12:54:13');
INSERT INTO public."question"(user_id, title, text, date) VALUES(28, 'a tree in python', 'How can I implement a tree in python?', '2021-01-28 01:51:13');
INSERT INTO public."question"(user_id, title, text, date) VALUES(47, 'a tree in javascript', 'How can I implement a tree in javascript?', '2021-01-14 21:27:09');
INSERT INTO public."question"(user_id, title, text, date) VALUES(14, 'a tree in java', 'How can I implement a tree in java?', '2021-01-15 13:11:48');
INSERT INTO public."question"(user_id, title, text, date) VALUES(51, 'a tree in swipl', 'How can I implement a tree in swipl?', '2021-05-19 05:36:29');
INSERT INTO public."question"(user_id, title, text, date) VALUES(28, 'a set in c++', 'How can I implement a set in c++?', '2021-03-17 08:45:04');
INSERT INTO public."question"(user_id, title, text, date) VALUES(14, 'a set in python', 'How can I implement a set in python?', '2021-01-20 12:08:54');
INSERT INTO public."question"(user_id, title, text, date) VALUES(46, 'a set in javascript', 'How can I implement a set in javascript?', '2021-02-25 18:18:46');
INSERT INTO public."question"(user_id, title, text, date) VALUES(40, 'a set in java', 'How can I implement a set in java?', '2021-01-21 23:49:19');
INSERT INTO public."question"(user_id, title, text, date) VALUES(31, 'a set in swipl', 'How can I implement a set in swipl?', '2021-04-19 07:41:36');
INSERT INTO public."question"(user_id, title, text, date) VALUES(14, 'a dictionary in c++', 'How can I implement a dictionary in c++?', '2020-10-06 12:35:18');
INSERT INTO public."question"(user_id, title, text, date) VALUES(48, 'a dictionary in python', 'How can I implement a dictionary in python?', '2021-01-19 01:11:53');
INSERT INTO public."question"(user_id, title, text, date) VALUES(3, 'a dictionary in javascript', 'How can I implement a dictionary in javascript?', '2021-01-02 20:41:58');
INSERT INTO public."question"(user_id, title, text, date) VALUES(9, 'a dictionary in java', 'How can I implement a dictionary in java?', '2021-04-16 17:48:47');
INSERT INTO public."question"(user_id, title, text, date) VALUES(22, 'a dictionary in swipl', 'How can I implement a dictionary in swipl?', '2021-04-19 00:37:34');
INSERT INTO public."question"(user_id, title, text, date) VALUES(24, 'a min heap in c++', 'How can I implement a min heap in c++?', '2021-03-20 17:30:52');
INSERT INTO public."question"(user_id, title, text, date) VALUES(24, 'a min heap in python', 'How can I implement a min heap in python?', '2021-03-28 23:58:10');
INSERT INTO public."question"(user_id, title, text, date) VALUES(11, 'a min heap in javascript', 'How can I implement a min heap in javascript?', '2021-02-16 05:46:52');
INSERT INTO public."question"(user_id, title, text, date) VALUES(21, 'a min heap in java', 'How can I implement a min heap in java?', '2021-03-09 06:47:04');
INSERT INTO public."question"(user_id, title, text, date) VALUES(37, 'a min heap in swipl', 'How can I implement a min heap in swipl?', '2021-04-26 17:27:27');
INSERT INTO public."question"(user_id, title, text, date) VALUES(25, 'a max heap in c++', 'How can I implement a max heap in c++?', '2021-02-14 04:20:23');
INSERT INTO public."question"(user_id, title, text, date) VALUES(13, 'a max heap in python', 'How can I implement a max heap in python?', '2021-04-16 05:33:14');
INSERT INTO public."question"(user_id, title, text, date) VALUES(27, 'a max heap in javascript', 'How can I implement a max heap in javascript?', '2021-05-28 20:52:17');
INSERT INTO public."question"(user_id, title, text, date) VALUES(41, 'a max heap in java', 'How can I implement a max heap in java?', '2021-01-16 16:31:23');
INSERT INTO public."question"(user_id, title, text, date) VALUES(34, 'a max heap in swipl', 'How can I implement a max heap in swipl?', '2021-01-12 03:35:37');
INSERT INTO public."question"(user_id, title, text, date) VALUES(18, 'center text in html', 'How can I center text with html?', '2021-02-18 05:41:13');
INSERT INTO public."question"(user_id, title, text, date) VALUES(18, 'center text in css', 'How can I center text with css?', '2021-03-20 23:29:25');
INSERT INTO public."question"(user_id, title, text, date) VALUES(32, 'center text in javascript', 'How can I center text with javascript?', '2020-11-15 10:37:38');
INSERT INTO public."question"(user_id, title, text, date) VALUES(32, 'center text in react', 'How can I center text with react?', '2021-02-26 03:50:24');
INSERT INTO public."question"(user_id, title, text, date) VALUES(18, 'center text in angular', 'How can I center text with angular?', '2021-03-19 14:32:03');
INSERT INTO public."question"(user_id, title, text, date) VALUES(23, 'change background color in html', 'How can I change background color with html?', '2020-06-24 15:05:27');
INSERT INTO public."question"(user_id, title, text, date) VALUES(23, 'change background color in css', 'How can I change background color with css?', '2020-07-03 07:51:47');
INSERT INTO public."question"(user_id, title, text, date) VALUES(31, 'change background color in javascript', 'How can I change background color with javascript?', '2020-10-19 21:10:31');
INSERT INTO public."question"(user_id, title, text, date) VALUES(26, 'change background color in react', 'How can I change background color with react?', '2020-11-27 10:01:22');
INSERT INTO public."question"(user_id, title, text, date) VALUES(32, 'change background color in angular', 'How can I change background color with angular?', '2020-04-11 11:46:21');
INSERT INTO public."question"(user_id, title, text, date) VALUES(47, 'create a form in html', 'How can I create a form with html?', '2020-03-04 05:55:10');
INSERT INTO public."question"(user_id, title, text, date) VALUES(29, 'create a form in css', 'How can I create a form with css?', '2021-03-13 06:30:28');
INSERT INTO public."question"(user_id, title, text, date) VALUES(40, 'create a form in javascript', 'How can I create a form with javascript?', '2020-06-24 15:38:02');
INSERT INTO public."question"(user_id, title, text, date) VALUES(33, 'create a form in react', 'How can I create a form with react?', '2020-10-17 19:40:24');
INSERT INTO public."question"(user_id, title, text, date) VALUES(8, 'create a form in angular', 'How can I create a form with angular?', '2021-03-28 01:31:35');
INSERT INTO public."question"(user_id, title, text, date) VALUES(12, 'add dark mode in html', 'How can I add dark mode with html?', '2021-04-20 20:40:19');
INSERT INTO public."question"(user_id, title, text, date) VALUES(48, 'add dark mode in css', 'How can I add dark mode with css?', '2020-03-15 01:50:12');
INSERT INTO public."question"(user_id, title, text, date) VALUES(31, 'add dark mode in javascript', 'How can I add dark mode with javascript?', '2021-05-05 05:47:39');
INSERT INTO public."question"(user_id, title, text, date) VALUES(7, 'add dark mode in react', 'How can I add dark mode with react?', '2021-04-20 10:11:40');
INSERT INTO public."question"(user_id, title, text, date) VALUES(14, 'add dark mode in angular', 'How can I add dark mode with angular?', '2021-02-04 01:16:15');
INSERT INTO public."question"(user_id, title, text, date) VALUES(50, 'add animation in html', 'How can I add animation with html?', '2021-05-17 23:43:03');
INSERT INTO public."question"(user_id, title, text, date) VALUES(7, 'add animation in css', 'How can I add animation with css?', '2021-03-20 06:35:32');
INSERT INTO public."question"(user_id, title, text, date) VALUES(47, 'add animation in javascript', 'How can I add animation with javascript?', '2021-02-16 09:30:25');
INSERT INTO public."question"(user_id, title, text, date) VALUES(23, 'add animation in react', 'How can I add animation with react?', '2020-12-04 12:11:39');
INSERT INTO public."question"(user_id, title, text, date) VALUES(29, 'add animation in angular', 'How can I add animation with angular?', '2021-01-10 18:10:30');
INSERT INTO public."question"(user_id, title, text, date) VALUES(34, 'change background in ubuntu', 'How can I change background in ubuntu?', '2020-11-26 06:47:17');
INSERT INTO public."question"(user_id, title, text, date) VALUES(18, 'change background in linux', 'How can I change background in linux?', '2021-04-24 19:38:33');
INSERT INTO public."question"(user_id, title, text, date) VALUES(9, 'change background in windows', 'How can I change background in windows?', '2021-01-23 23:08:29');
INSERT INTO public."question"(user_id, title, text, date) VALUES(28, 'install vscode in ubuntu', 'How can I install vscode in ubuntu?', '2020-02-08 19:21:12');
INSERT INTO public."question"(user_id, title, text, date) VALUES(13, 'install vscode in linux', 'How can I install vscode in linux?', '2021-03-04 10:38:18');
INSERT INTO public."question"(user_id, title, text, date) VALUES(49, 'install vscode in windows', 'How can I install vscode in windows?', '2021-05-02 21:51:35');
INSERT INTO public."question"(user_id, title, text, date) VALUES(51, 'delete a directory in ubuntu', 'How can I delete a directory in ubuntu?', '2020-04-14 01:13:48');
INSERT INTO public."question"(user_id, title, text, date) VALUES(28, 'delete a directory in linux', 'How can I delete a directory in linux?', '2021-02-16 01:55:46');
INSERT INTO public."question"(user_id, title, text, date) VALUES(24, 'delete a directory in windows', 'How can I delete a directory in windows?', '2021-03-25 15:34:57');
INSERT INTO public."question"(user_id, title, text, date) VALUES(50, 'rename a directory in ubuntu', 'How can I rename a directory in ubuntu?', '2021-01-16 22:17:53');
INSERT INTO public."question"(user_id, title, text, date) VALUES(35, 'rename a directory in linux', 'How can I rename a directory in linux?', '2021-02-06 13:20:51');
INSERT INTO public."question"(user_id, title, text, date) VALUES(4, 'rename a directory in windows', 'How can I rename a directory in windows?', '2021-03-28 23:17:53');
INSERT INTO public."question"(user_id, title, text, date) VALUES(9, 'download chrome in ubuntu', 'How can I download chrome in ubuntu?', '2021-03-12 13:07:40');
INSERT INTO public."question"(user_id, title, text, date) VALUES(38, 'download chrome in linux', 'How can I download chrome in linux?', '2021-05-26 03:43:12');
INSERT INTO public."question"(user_id, title, text, date) VALUES(31, 'download chrome in windows', 'How can I download chrome in windows?', '2021-01-21 04:44:05');
INSERT INTO public."question"(user_id, title, text, date) VALUES(50, 'keep a backup in ubuntu', 'How can I keep a backup in ubuntu?', '2020-11-11 02:37:28');
INSERT INTO public."question"(user_id, title, text, date) VALUES(34, 'keep a backup in linux', 'How can I keep a backup in linux?', '2020-10-01 05:39:46');
INSERT INTO public."question"(user_id, title, text, date) VALUES(22, 'keep a backup in windows', 'How can I keep a backup in windows?', '2021-01-13 08:13:36');
INSERT INTO public."question"(user_id, title, text, date) VALUES(11, 'switch language in ubuntu', 'How can I switch language in ubuntu?', '2021-03-18 05:26:43');
INSERT INTO public."question"(user_id, title, text, date) VALUES(23, 'switch language in linux', 'How can I switch language in linux?', '2021-02-07 19:41:49');
INSERT INTO public."question"(user_id, title, text, date) VALUES(44, 'switch language in windows', 'How can I switch language in windows?', '2021-04-27 20:18:15');

INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(1, 61, '2021-06-22 04:01:13');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(2, 108, '2021-06-27 17:02:39');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(2, 130, '2021-06-10 14:13:52');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(2, 96, '2020-12-19 04:09:22');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(3, 66, '2021-06-10 12:52:37');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(4, 77, '2021-06-21 22:29:38');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(4, 73, '2021-05-21 07:29:54');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(4, 75, '2021-02-04 12:47:12');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(4, 32, '2021-06-13 22:13:11');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(5, 94, '2021-06-04 22:52:04');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(5, 42, '2021-05-28 02:20:09');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(6, 76, '2021-06-17 21:10:28');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(7, 58, '2021-06-24 14:19:52');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(7, 31, '2021-02-16 16:21:51');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(7, 22, '2021-01-18 00:13:50');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(8, 106, '2021-05-18 07:05:24');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(8, 3, '2021-05-01 23:08:38');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(8, 1, '2021-04-01 11:30:50');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(9, 118, '2021-05-22 21:48:41');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(9, 130, '2021-05-22 00:09:44');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(9, 128, '2020-11-19 05:22:02');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(10, 2, '2021-04-30 19:42:15');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(10, 45, '2021-06-18 22:24:48');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(11, 15, '2021-06-01 05:11:34');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(11, 108, '2021-05-24 14:42:30');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(11, 113, '2021-01-24 16:53:08');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(11, 126, '2021-06-25 10:52:12');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(12, 28, '2021-06-27 21:36:06');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(12, 2, '2021-05-06 06:48:40');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(12, 99, '2021-03-14 19:29:44');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(13, 117, '2021-06-22 17:45:34');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(13, 13, '2021-06-10 01:56:47');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(14, 82, '2021-05-12 01:45:39');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(14, 13, '2021-05-22 06:22:39');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(15, 85, '2021-06-07 15:14:32');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(15, 10, '2021-03-26 23:50:50');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(15, 115, '2021-06-08 11:19:27');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(15, 110, '2021-05-03 21:30:14');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(16, 59, '2021-04-02 02:16:56');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(16, 94, '2021-03-18 22:58:52');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(16, 18, '2021-06-08 23:13:41');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(17, 66, '2021-01-24 13:05:07');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(17, 94, '2020-07-16 02:20:36');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(17, 55, '2021-03-27 08:39:57');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(17, 64, '2021-02-27 18:58:02');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(18, 13, '2021-06-09 18:07:39');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(18, 41, '2021-04-22 14:55:55');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(18, 80, '2021-05-24 15:52:02');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(18, 131, '2021-05-30 23:15:53');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(19, 132, '2021-04-21 15:22:59');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(19, 8, '2021-06-10 09:40:51');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(19, 10, '2021-06-05 13:45:27');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(20, 24, '2021-05-25 06:50:16');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(20, 8, '2021-06-18 06:04:59');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(20, 32, '2021-05-29 02:23:42');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(20, 100, '2020-12-04 10:45:45');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(21, 109, '2021-03-27 20:18:48');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(21, 40, '2021-06-04 02:24:59');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(22, 93, '2020-07-24 19:21:51');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(22, 4, '2021-05-02 10:07:34');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(22, 85, '2021-06-21 14:42:00');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(23, 30, '2021-04-27 06:17:35');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(24, 115, '2021-04-27 22:55:53');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(24, 71, '2021-04-25 23:35:40');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(25, 35, '2021-02-20 19:46:41');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(26, 99, '2021-05-28 11:41:29');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(27, 9, '2020-11-08 14:05:05');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(27, 65, '2021-04-09 23:41:33');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(27, 122, '2021-04-10 03:00:27');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(28, 60, '2021-02-14 04:47:54');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(28, 109, '2021-06-17 08:00:14');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(29, 26, '2021-06-08 05:14:52');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(30, 61, '2021-06-03 23:52:31');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(30, 58, '2021-06-22 00:04:48');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(30, 86, '2021-03-19 10:15:03');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(31, 117, '2021-05-16 17:13:08');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(31, 107, '2021-02-24 00:00:56');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(31, 42, '2021-06-21 10:34:18');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(32, 6, '2021-03-16 02:59:32');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(33, 72, '2021-04-23 12:17:41');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(33, 127, '2021-06-20 14:58:21');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(33, 20, '2021-02-13 10:18:39');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(34, 52, '2020-05-27 01:39:44');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(34, 31, '2020-11-22 14:45:35');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(34, 68, '2021-06-28 12:40:47');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(34, 56, '2020-10-18 21:59:17');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(35, 75, '2021-05-28 23:15:47');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(35, 70, '2021-06-19 23:52:57');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(36, 98, '2021-06-12 05:32:24');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(36, 74, '2021-06-19 16:21:18');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(37, 100, '2020-07-21 17:02:31');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(37, 94, '2020-09-07 16:57:03');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(37, 15, '2021-03-27 17:39:16');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(37, 122, '2021-06-14 05:31:33');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(38, 124, '2021-04-15 16:18:08');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(38, 131, '2021-03-26 04:30:26');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(38, 114, '2021-06-18 03:04:55');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(39, 61, '2021-05-16 01:40:56');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(39, 119, '2021-02-25 19:40:06');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(40, 18, '2021-05-30 14:56:07');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(40, 133, '2021-05-11 00:10:45');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(40, 121, '2021-06-27 12:36:36');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(40, 56, '2021-01-31 11:19:07');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(41, 115, '2021-05-11 11:00:40');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(42, 1, '2021-03-24 11:15:13');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(42, 7, '2021-05-17 21:38:42');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(42, 105, '2021-06-03 16:45:10');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(42, 63, '2021-05-12 16:00:33');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(43, 67, '2021-06-18 20:52:11');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(43, 127, '2021-04-18 23:13:40');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(44, 25, '2021-06-13 11:45:19');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(45, 110, '2021-03-14 21:05:18');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(45, 42, '2021-06-27 19:52:13');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(45, 45, '2020-09-30 07:22:09');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(45, 54, '2021-04-26 07:54:30');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(46, 9, '2021-01-05 22:10:52');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(47, 125, '2021-05-04 16:42:18');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(47, 81, '2021-06-08 21:30:26');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(47, 55, '2021-04-16 20:03:09');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(48, 94, '2020-11-04 07:10:20');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(48, 40, '2021-05-23 23:09:50');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(49, 33, '2021-06-05 12:53:11');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(49, 86, '2021-02-21 23:57:06');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(50, 92, '2021-04-03 18:57:50');
INSERT INTO public."questionupvote"(user_id, question_id, date) VALUES(51, 77, '2021-05-04 07:40:39');

INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(1, 10);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(1, 11);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(2, 11);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(3, 11);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(4, 11);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(5, 11);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(6, 1);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(6, 11);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(7, 2);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(7, 11);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(8, 5);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(8, 11);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(9, 10);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(9, 11);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(10, 11);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(11, 11);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(12, 11);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(13, 11);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(14, 1);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(14, 11);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(15, 2);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(15, 11);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(16, 5);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(16, 11);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(17, 10);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(17, 11);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(18, 11);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(19, 11);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(20, 11);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(21, 11);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(22, 1);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(22, 11);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(23, 2);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(23, 11);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(24, 5);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(24, 11);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(25, 10);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(25, 11);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(26, 11);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(27, 11);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(28, 11);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(29, 11);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(30, 1);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(30, 11);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(31, 2);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(31, 11);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(32, 5);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(32, 11);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(33, 7);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(33, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(33, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(34, 6);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(34, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(34, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(35, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(35, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(36, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(36, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(37, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(37, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(38, 7);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(38, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(38, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(39, 6);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(39, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(39, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(40, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(40, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(41, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(41, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(42, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(42, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(43, 7);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(43, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(43, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(44, 6);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(44, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(44, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(45, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(45, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(46, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(46, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(47, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(47, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(48, 7);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(48, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(48, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(49, 6);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(49, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(49, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(50, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(50, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(51, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(51, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(52, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(52, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(53, 7);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(53, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(53, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(54, 6);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(54, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(54, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(55, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(55, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(56, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(56, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(57, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(57, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(58, 7);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(58, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(58, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(59, 6);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(59, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(59, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(60, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(60, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(61, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(61, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(62, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(62, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(63, 7);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(63, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(63, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(64, 6);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(64, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(64, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(65, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(65, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(66, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(66, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(67, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(67, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(68, 7);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(68, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(68, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(69, 6);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(69, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(69, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(70, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(70, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(71, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(71, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(72, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(72, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(73, 7);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(73, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(73, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(74, 6);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(74, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(74, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(75, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(75, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(76, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(76, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(77, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(77, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(78, 7);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(78, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(78, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(79, 6);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(79, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(79, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(80, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(80, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(81, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(81, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(82, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(82, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(83, 7);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(83, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(83, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(84, 6);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(84, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(84, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(85, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(85, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(86, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(86, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(87, 8);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(87, 9);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(88, 16);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(89, 17);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(91, 19);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(92, 20);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(93, 16);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(94, 17);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(96, 19);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(97, 20);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(98, 16);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(99, 17);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(101, 19);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(102, 20);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(103, 16);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(104, 17);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(106, 19);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(107, 20);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(108, 16);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(109, 17);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(111, 19);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(112, 20);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(113, 25);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(114, 26);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(115, 27);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(116, 25);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(117, 26);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(118, 27);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(119, 25);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(120, 26);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(121, 27);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(122, 25);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(123, 26);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(124, 27);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(125, 25);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(126, 26);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(127, 27);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(128, 25);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(129, 26);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(130, 27);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(131, 25);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(132, 26);
INSERT INTO public."question_keyword"(question_id, keyword_id) VALUES(133, 27);

