INSERT INTO public."question"("ownerId", title, text) VALUES(16, 'insert in sql', 'What is the fastest way to insert data in sql?');
INSERT INTO public."question"("ownerId", title, text) VALUES(10, 'insert in mongodb', 'What is the fastest way to insert data in mongodb?');
INSERT INTO public."question"("ownerId", title, text) VALUES(42, 'insert in relational databases', 'What is the fastest way to insert data in relational databases?');
INSERT INTO public."question"("ownerId", title, text) VALUES(47, 'insert in non-relational databases', 'What is the fastest way to insert data in non-relational databases?');
INSERT INTO public."question"("ownerId", title, text) VALUES(11, 'insert in Django', 'What is the fastest way to insert data in Django?');
INSERT INTO public."question"("ownerId", title, text) VALUES(28, 'insert in Spring boot', 'What is the fastest way to insert data in Spring boot?');
INSERT INTO public."question"("ownerId", title, text) VALUES(47, 'insert in Laravel', 'What is the fastest way to insert data in Laravel?');
INSERT INTO public."question"("ownerId", title, text) VALUES(34, 'delete in sql', 'What is the fastest way to delete data in sql?');
INSERT INTO public."question"("ownerId", title, text) VALUES(10, 'delete in postgresql', 'What is the fastest way to delete data in postgresql?');
INSERT INTO public."question"("ownerId", title, text) VALUES(28, 'delete in mongodb', 'What is the fastest way to delete data in mongodb?');
INSERT INTO public."question"("ownerId", title, text) VALUES(15, 'delete in relational databases', 'What is the fastest way to delete data in relational databases?');
INSERT INTO public."question"("ownerId", title, text) VALUES(25, 'delete in Django', 'What is the fastest way to delete data in Django?');
INSERT INTO public."question"("ownerId", title, text) VALUES(43, 'delete in Spring boot', 'What is the fastest way to delete data in Spring boot?');
INSERT INTO public."question"("ownerId", title, text) VALUES(12, 'delete in Laravel', 'What is the fastest way to delete data in Laravel?');
INSERT INTO public."question"("ownerId", title, text) VALUES(33, 'update in sql', 'What is the fastest way to update data in sql?');
INSERT INTO public."question"("ownerId", title, text) VALUES(7, 'update in postgresql', 'What is the fastest way to update data in postgresql?');
INSERT INTO public."question"("ownerId", title, text) VALUES(25, 'update in mongodb', 'What is the fastest way to update data in mongodb?');
INSERT INTO public."question"("ownerId", title, text) VALUES(15, 'update in relational databases', 'What is the fastest way to update data in relational databases?');
INSERT INTO public."question"("ownerId", title, text) VALUES(18, 'update in non-relational databases', 'What is the fastest way to update data in non-relational databases?');
INSERT INTO public."question"("ownerId", title, text) VALUES(43, 'update in Django', 'What is the fastest way to update data in Django?');
INSERT INTO public."question"("ownerId", title, text) VALUES(30, 'update in Spring boot', 'What is the fastest way to update data in Spring boot?');
INSERT INTO public."question"("ownerId", title, text) VALUES(24, 'update in Laravel', 'What is the fastest way to update data in Laravel?');
INSERT INTO public."question"("ownerId", title, text) VALUES(33, 'read in sql', 'What is the fastest way to read data in sql?');
INSERT INTO public."question"("ownerId", title, text) VALUES(17, 'read in postgresql', 'What is the fastest way to read data in postgresql?');
INSERT INTO public."question"("ownerId", title, text) VALUES(15, 'read in relational databases', 'What is the fastest way to read data in relational databases?');
INSERT INTO public."question"("ownerId", title, text) VALUES(8, 'read in non-relational databases', 'What is the fastest way to read data in non-relational databases?');
INSERT INTO public."question"("ownerId", title, text) VALUES(25, 'read in Django', 'What is the fastest way to read data in Django?');
INSERT INTO public."question"("ownerId", title, text) VALUES(14, 'read in Spring boot', 'What is the fastest way to read data in Spring boot?');
INSERT INTO public."question"("ownerId", title, text) VALUES(47, 'read in Laravel', 'What is the fastest way to read data in Laravel?');
INSERT INTO public."question"("ownerId", title, text) VALUES(41, 'an array in c++', 'How can I implement an array in c++?');
INSERT INTO public."question"("ownerId", title, text) VALUES(31, 'an array in Python', 'How can I implement an array in Python?');
INSERT INTO public."question"("ownerId", title, text) VALUES(27, 'an array in java', 'How can I implement an array in java?');
INSERT INTO public."question"("ownerId", title, text) VALUES(21, 'an array in swipl', 'How can I implement an array in swipl?');
INSERT INTO public."question"("ownerId", title, text) VALUES(20, 'a linked list in c++', 'How can I implement a linked list in c++?');
INSERT INTO public."question"("ownerId", title, text) VALUES(26, 'a linked list in Python', 'How can I implement a linked list in Python?');
INSERT INTO public."question"("ownerId", title, text) VALUES(38, 'a linked list in javascript', 'How can I implement a linked list in javascript?');
INSERT INTO public."question"("ownerId", title, text) VALUES(37, 'a linked list in java', 'How can I implement a linked list in java?');
INSERT INTO public."question"("ownerId", title, text) VALUES(32, 'a linked list in swipl', 'How can I implement a linked list in swipl?');
INSERT INTO public."question"("ownerId", title, text) VALUES(19, 'a queue in c++', 'How can I implement a queue in c++?');
INSERT INTO public."question"("ownerId", title, text) VALUES(7, 'a queue in Python', 'How can I implement a queue in Python?');
INSERT INTO public."question"("ownerId", title, text) VALUES(37, 'a queue in javascript', 'How can I implement a queue in javascript?');
INSERT INTO public."question"("ownerId", title, text) VALUES(41, 'a queue in java', 'How can I implement a queue in java?');
INSERT INTO public."question"("ownerId", title, text) VALUES(49, 'a queue in swipl', 'How can I implement a queue in swipl?');
INSERT INTO public."question"("ownerId", title, text) VALUES(9, 'a priority queue in c++', 'How can I implement a priority queue in c++?');
INSERT INTO public."question"("ownerId", title, text) VALUES(40, 'a priority queue in Python', 'How can I implement a priority queue in Python?');
INSERT INTO public."question"("ownerId", title, text) VALUES(7, 'a priority queue in javascript', 'How can I implement a priority queue in javascript?');
INSERT INTO public."question"("ownerId", title, text) VALUES(41, 'a priority queue in swipl', 'How can I implement a priority queue in swipl?');
INSERT INTO public."question"("ownerId", title, text) VALUES(23, 'a stack in c++', 'How can I implement a stack in c++?');
INSERT INTO public."question"("ownerId", title, text) VALUES(18, 'a stack in Python', 'How can I implement a stack in Python?');
INSERT INTO public."question"("ownerId", title, text) VALUES(38, 'a stack in javascript', 'How can I implement a stack in javascript?');
INSERT INTO public."question"("ownerId", title, text) VALUES(30, 'a stack in java', 'How can I implement a stack in java?');
INSERT INTO public."question"("ownerId", title, text) VALUES(22, 'a stack in swipl', 'How can I implement a stack in swipl?');
INSERT INTO public."question"("ownerId", title, text) VALUES(46, 'a graph in c++', 'How can I implement a graph in c++?');
INSERT INTO public."question"("ownerId", title, text) VALUES(21, 'a graph in Python', 'How can I implement a graph in Python?');
INSERT INTO public."question"("ownerId", title, text) VALUES(10, 'a graph in javascript', 'How can I implement a graph in javascript?');
INSERT INTO public."question"("ownerId", title, text) VALUES(46, 'a graph in java', 'How can I implement a graph in java?');
INSERT INTO public."question"("ownerId", title, text) VALUES(27, 'a graph in swipl', 'How can I implement a graph in swipl?');
INSERT INTO public."question"("ownerId", title, text) VALUES(45, 'a tree in c++', 'How can I implement a tree in c++?');
INSERT INTO public."question"("ownerId", title, text) VALUES(12, 'a tree in Python', 'How can I implement a tree in Python?');
INSERT INTO public."question"("ownerId", title, text) VALUES(31, 'a tree in javascript', 'How can I implement a tree in javascript?');
INSERT INTO public."question"("ownerId", title, text) VALUES(46, 'a tree in java', 'How can I implement a tree in java?');
INSERT INTO public."question"("ownerId", title, text) VALUES(30, 'a tree in swipl', 'How can I implement a tree in swipl?');
INSERT INTO public."question"("ownerId", title, text) VALUES(16, 'a set in c++', 'How can I implement a set in c++?');
INSERT INTO public."question"("ownerId", title, text) VALUES(37, 'a set in Python', 'How can I implement a set in Python?');
INSERT INTO public."question"("ownerId", title, text) VALUES(36, 'a set in javascript', 'How can I implement a set in javascript?');
INSERT INTO public."question"("ownerId", title, text) VALUES(44, 'a set in java', 'How can I implement a set in java?');
INSERT INTO public."question"("ownerId", title, text) VALUES(21, 'a dictionary in c++', 'How can I implement a dictionary in c++?');
INSERT INTO public."question"("ownerId", title, text) VALUES(10, 'a dictionary in Python', 'How can I implement a dictionary in Python?');
INSERT INTO public."question"("ownerId", title, text) VALUES(43, 'a dictionary in javascript', 'How can I implement a dictionary in javascript?');
INSERT INTO public."question"("ownerId", title, text) VALUES(21, 'a dictionary in java', 'How can I implement a dictionary in java?');
INSERT INTO public."question"("ownerId", title, text) VALUES(43, 'a dictionary in swipl', 'How can I implement a dictionary in swipl?');
INSERT INTO public."question"("ownerId", title, text) VALUES(28, 'a min heap in c++', 'How can I implement a min heap in c++?');
INSERT INTO public."question"("ownerId", title, text) VALUES(10, 'a min heap in Python', 'How can I implement a min heap in Python?');
INSERT INTO public."question"("ownerId", title, text) VALUES(30, 'a min heap in javascript', 'How can I implement a min heap in javascript?');
INSERT INTO public."question"("ownerId", title, text) VALUES(27, 'a min heap in java', 'How can I implement a min heap in java?');
INSERT INTO public."question"("ownerId", title, text) VALUES(41, 'a min heap in swipl', 'How can I implement a min heap in swipl?');
INSERT INTO public."question"("ownerId", title, text) VALUES(33, 'a max heap in c++', 'How can I implement a max heap in c++?');
INSERT INTO public."question"("ownerId", title, text) VALUES(35, 'a max heap in Python', 'How can I implement a max heap in Python?');
INSERT INTO public."question"("ownerId", title, text) VALUES(26, 'a max heap in javascript', 'How can I implement a max heap in javascript?');
INSERT INTO public."question"("ownerId", title, text) VALUES(8, 'center text in html', 'How can I center text with html?');
INSERT INTO public."question"("ownerId", title, text) VALUES(22, 'center text in css', 'How can I center text with css?');
INSERT INTO public."question"("ownerId", title, text) VALUES(20, 'center text in javascript', 'How can I center text with javascript?');
INSERT INTO public."question"("ownerId", title, text) VALUES(28, 'center text in react', 'How can I center text with react?');
INSERT INTO public."question"("ownerId", title, text) VALUES(28, 'center text in angular', 'How can I center text with angular?');
INSERT INTO public."question"("ownerId", title, text) VALUES(8, 'change background color in html', 'How can I change background color with html?');
INSERT INTO public."question"("ownerId", title, text) VALUES(46, 'change background color in css', 'How can I change background color with css?');
INSERT INTO public."question"("ownerId", title, text) VALUES(12, 'change background color in react', 'How can I change background color with react?');
INSERT INTO public."question"("ownerId", title, text) VALUES(18, 'change background color in angular', 'How can I change background color with angular?');
INSERT INTO public."question"("ownerId", title, text) VALUES(48, 'create a form in css', 'How can I create a form with css?');
INSERT INTO public."question"("ownerId", title, text) VALUES(34, 'create a form in javascript', 'How can I create a form with javascript?');
INSERT INTO public."question"("ownerId", title, text) VALUES(12, 'create a form in react', 'How can I create a form with react?');
INSERT INTO public."question"("ownerId", title, text) VALUES(28, 'create a form in angular', 'How can I create a form with angular?');
INSERT INTO public."question"("ownerId", title, text) VALUES(39, 'add dark mode in html', 'How can I add dark mode with html?');
INSERT INTO public."question"("ownerId", title, text) VALUES(42, 'add dark mode in css', 'How can I add dark mode with css?');
INSERT INTO public."question"("ownerId", title, text) VALUES(43, 'add dark mode in react', 'How can I add dark mode with react?');
INSERT INTO public."question"("ownerId", title, text) VALUES(40, 'add dark mode in angular', 'How can I add dark mode with angular?');
INSERT INTO public."question"("ownerId", title, text) VALUES(10, 'add animation in html', 'How can I add animation with html?');
INSERT INTO public."question"("ownerId", title, text) VALUES(9, 'add animation in css', 'How can I add animation with css?');
INSERT INTO public."question"("ownerId", title, text) VALUES(47, 'add animation in javascript', 'How can I add animation with javascript?');
INSERT INTO public."question"("ownerId", title, text) VALUES(35, 'add animation in react', 'How can I add animation with react?');
INSERT INTO public."question"("ownerId", title, text) VALUES(20, 'add animation in angular', 'How can I add animation with angular?');
INSERT INTO public."question"("ownerId", title, text) VALUES(44, 'change background in ubuntu', 'How can I change background in ubuntu?');
INSERT INTO public."question"("ownerId", title, text) VALUES(10, 'change background in linux', 'How can I change background in linux?');
INSERT INTO public."question"("ownerId", title, text) VALUES(9, 'change background in windows', 'How can I change background in windows?');
INSERT INTO public."question"("ownerId", title, text) VALUES(28, 'install vscode in ubuntu', 'How can I install vscode in ubuntu?');
INSERT INTO public."question"("ownerId", title, text) VALUES(45, 'install vscode in linux', 'How can I install vscode in linux?');
INSERT INTO public."question"("ownerId", title, text) VALUES(19, 'install vscode in windows', 'How can I install vscode in windows?');
INSERT INTO public."question"("ownerId", title, text) VALUES(30, 'delete a directory in ubuntu', 'How can I delete a directory in ubuntu?');
INSERT INTO public."question"("ownerId", title, text) VALUES(10, 'delete a directory in linux', 'How can I delete a directory in linux?');
INSERT INTO public."question"("ownerId", title, text) VALUES(14, 'delete a directory in windows', 'How can I delete a directory in windows?');
INSERT INTO public."question"("ownerId", title, text) VALUES(31, 'rename a directory in ubuntu', 'How can I rename a directory in ubuntu?');
INSERT INTO public."question"("ownerId", title, text) VALUES(32, 'rename a directory in linux', 'How can I rename a directory in linux?');
INSERT INTO public."question"("ownerId", title, text) VALUES(16, 'download chrome in ubuntu', 'How can I download chrome in ubuntu?');
INSERT INTO public."question"("ownerId", title, text) VALUES(43, 'download chrome in linux', 'How can I download chrome in linux?');
INSERT INTO public."question"("ownerId", title, text) VALUES(11, 'download chrome in windows', 'How can I download chrome in windows?');
INSERT INTO public."question"("ownerId", title, text) VALUES(27, 'keep a backup in ubuntu', 'How can I keep a backup in ubuntu?');
INSERT INTO public."question"("ownerId", title, text) VALUES(35, 'keep a backup in linux', 'How can I keep a backup in linux?');
INSERT INTO public."question"("ownerId", title, text) VALUES(9, 'keep a backup in windows', 'How can I keep a backup in windows?');
INSERT INTO public."question"("ownerId", title, text) VALUES(28, 'switch language in ubuntu', 'How can I switch language in ubuntu?');
INSERT INTO public."question"("ownerId", title, text) VALUES(9, 'switch language in linux', 'How can I switch language in linux?');
INSERT INTO public."question"("ownerId", title, text) VALUES(40, 'switch language in windows', 'How can I switch language in windows?');
