INSERT INTO public."question"(user_id, title, text, date) VALUES(13, 'insert in mysql', 'What is the fastest way to insert data in mysql?', '2021-03-18 16:45:16');
INSERT INTO public."question"(user_id, title, text, date) VALUES(31, 'insert in postgresql', 'What is the fastest way to insert data in postgresql?', '2021-04-28 20:41:35');
INSERT INTO public."question"(user_id, title, text, date) VALUES(37, 'insert in mongodb', 'What is the fastest way to insert data in mongodb?', '2021-02-27 06:41:15');
INSERT INTO public."question"(user_id, title, text, date) VALUES(50, 'insert in relational databases', 'What is the fastest way to insert data in relational databases?', '2021-01-02 22:12:18');
INSERT INTO public."question"(user_id, title, text, date) VALUES(38, 'insert in non-relational databases', 'What is the fastest way to insert data in non-relational databases?', '2021-03-24 18:43:55');
INSERT INTO public."question"(user_id, title, text, date) VALUES(1, 'insert in django', 'What is the fastest way to insert data in django?', '2021-03-10 21:44:22');
INSERT INTO public."question"(user_id, title, text, date) VALUES(47, 'insert in spring boot', 'What is the fastest way to insert data in spring boot?', '2020-10-20 00:18:53');
INSERT INTO public."question"(user_id, title, text, date) VALUES(19, 'insert in laravel', 'What is the fastest way to insert data in laravel?', '2021-03-23 22:47:02');
INSERT INTO public."question"(user_id, title, text, date) VALUES(25, 'delete in mysql', 'What is the fastest way to delete data in mysql?', '2020-07-20 01:40:26');
INSERT INTO public."question"(user_id, title, text, date) VALUES(44, 'delete in postgresql', 'What is the fastest way to delete data in postgresql?', '2021-02-04 01:35:14');
INSERT INTO public."question"(user_id, title, text, date) VALUES(35, 'delete in mongodb', 'What is the fastest way to delete data in mongodb?', '2020-08-16 20:50:29');
INSERT INTO public."question"(user_id, title, text, date) VALUES(32, 'delete in relational databases', 'What is the fastest way to delete data in relational databases?', '2020-12-15 23:07:18');
INSERT INTO public."question"(user_id, title, text, date) VALUES(36, 'delete in non-relational databases', 'What is the fastest way to delete data in non-relational databases?', '2021-05-11 05:08:45');
INSERT INTO public."question"(user_id, title, text, date) VALUES(3, 'delete in django', 'What is the fastest way to delete data in django?', '2020-07-08 20:00:48');
INSERT INTO public."question"(user_id, title, text, date) VALUES(38, 'delete in spring boot', 'What is the fastest way to delete data in spring boot?', '2021-03-08 10:16:18');
INSERT INTO public."question"(user_id, title, text, date) VALUES(25, 'delete in laravel', 'What is the fastest way to delete data in laravel?', '2021-04-09 06:04:58');
INSERT INTO public."question"(user_id, title, text, date) VALUES(39, 'update in mysql', 'What is the fastest way to update data in mysql?', '2021-03-13 08:26:17');
INSERT INTO public."question"(user_id, title, text, date) VALUES(9, 'update in postgresql', 'What is the fastest way to update data in postgresql?', '2021-05-16 15:41:02');
INSERT INTO public."question"(user_id, title, text, date) VALUES(1, 'update in mongodb', 'What is the fastest way to update data in mongodb?', '2021-01-16 09:50:11');
INSERT INTO public."question"(user_id, title, text, date) VALUES(11, 'update in relational databases', 'What is the fastest way to update data in relational databases?', '2021-01-20 20:17:36');
INSERT INTO public."question"(user_id, title, text, date) VALUES(10, 'update in non-relational databases', 'What is the fastest way to update data in non-relational databases?', '2021-01-03 08:51:11');
INSERT INTO public."question"(user_id, title, text, date) VALUES(27, 'update in django', 'What is the fastest way to update data in django?', '2020-06-20 17:09:29');
INSERT INTO public."question"(user_id, title, text, date) VALUES(7, 'update in spring boot', 'What is the fastest way to update data in spring boot?', '2021-03-05 11:15:16');
INSERT INTO public."question"(user_id, title, text, date) VALUES(19, 'update in laravel', 'What is the fastest way to update data in laravel?', '2021-02-10 13:54:43');
INSERT INTO public."question"(user_id, title, text, date) VALUES(4, 'read in mysql', 'What is the fastest way to read data in mysql?', '2021-03-05 08:19:10');
INSERT INTO public."question"(user_id, title, text, date) VALUES(48, 'read in postgresql', 'What is the fastest way to read data in postgresql?', '2021-05-23 15:43:25');
INSERT INTO public."question"(user_id, title, text, date) VALUES(26, 'read in mongodb', 'What is the fastest way to read data in mongodb?', '2021-02-04 23:01:04');
INSERT INTO public."question"(user_id, title, text, date) VALUES(15, 'read in relational databases', 'What is the fastest way to read data in relational databases?', '2021-05-27 04:29:46');
INSERT INTO public."question"(user_id, title, text, date) VALUES(37, 'read in non-relational databases', 'What is the fastest way to read data in non-relational databases?', '2021-02-18 12:35:16');
INSERT INTO public."question"(user_id, title, text, date) VALUES(20, 'read in django', 'What is the fastest way to read data in django?', '2021-03-20 07:05:16');
INSERT INTO public."question"(user_id, title, text, date) VALUES(34, 'read in spring boot', 'What is the fastest way to read data in spring boot?', '2020-10-16 08:44:27');
INSERT INTO public."question"(user_id, title, text, date) VALUES(7, 'read in laravel', 'What is the fastest way to read data in laravel?', '2021-05-26 17:42:10');
INSERT INTO public."question"(user_id, title, text, date) VALUES(39, 'an array in c++', 'How can I implement an array in c++?', '2021-04-13 23:37:13');
INSERT INTO public."question"(user_id, title, text, date) VALUES(4, 'an array in python', 'How can I implement an array in python?', '2021-04-12 10:03:10');
INSERT INTO public."question"(user_id, title, text, date) VALUES(4, 'an array in javascript', 'How can I implement an array in javascript?', '2021-01-10 12:49:53');
INSERT INTO public."question"(user_id, title, text, date) VALUES(11, 'an array in java', 'How can I implement an array in java?', '2021-03-22 05:00:12');
INSERT INTO public."question"(user_id, title, text, date) VALUES(44, 'an array in swipl', 'How can I implement an array in swipl?', '2021-01-17 10:45:09');
INSERT INTO public."question"(user_id, title, text, date) VALUES(37, 'a linked list in c++', 'How can I implement a linked list in c++?', '2020-06-24 10:00:31');
INSERT INTO public."question"(user_id, title, text, date) VALUES(48, 'a linked list in python', 'How can I implement a linked list in python?', '2021-03-10 12:09:22');
INSERT INTO public."question"(user_id, title, text, date) VALUES(18, 'a linked list in javascript', 'How can I implement a linked list in javascript?', '2021-05-23 05:57:17');
INSERT INTO public."question"(user_id, title, text, date) VALUES(17, 'a linked list in java', 'How can I implement a linked list in java?', '2021-01-08 06:17:48');
INSERT INTO public."question"(user_id, title, text, date) VALUES(37, 'a linked list in swipl', 'How can I implement a linked list in swipl?', '2021-05-14 23:34:01');
INSERT INTO public."question"(user_id, title, text, date) VALUES(41, 'a queue in c++', 'How can I implement a queue in c++?', '2021-04-28 00:14:33');
INSERT INTO public."question"(user_id, title, text, date) VALUES(24, 'a queue in python', 'How can I implement a queue in python?', '2020-01-13 17:33:23');
INSERT INTO public."question"(user_id, title, text, date) VALUES(1, 'a queue in javascript', 'How can I implement a queue in javascript?', '2020-04-07 11:15:13');
INSERT INTO public."question"(user_id, title, text, date) VALUES(24, 'a queue in java', 'How can I implement a queue in java?', '2020-01-08 20:59:26');
INSERT INTO public."question"(user_id, title, text, date) VALUES(15, 'a queue in swipl', 'How can I implement a queue in swipl?', '2020-11-15 10:56:43');
INSERT INTO public."question"(user_id, title, text, date) VALUES(15, 'a priority queue in c++', 'How can I implement a priority queue in c++?', '2021-04-08 18:48:00');
INSERT INTO public."question"(user_id, title, text, date) VALUES(46, 'a priority queue in python', 'How can I implement a priority queue in python?', '2021-04-06 07:35:23');
INSERT INTO public."question"(user_id, title, text, date) VALUES(21, 'a priority queue in javascript', 'How can I implement a priority queue in javascript?', '2021-05-13 10:25:15');
INSERT INTO public."question"(user_id, title, text, date) VALUES(40, 'a priority queue in java', 'How can I implement a priority queue in java?', '2021-03-21 21:38:09');
INSERT INTO public."question"(user_id, title, text, date) VALUES(49, 'a priority queue in swipl', 'How can I implement a priority queue in swipl?', '2020-02-01 00:59:05');
INSERT INTO public."question"(user_id, title, text, date) VALUES(35, 'a stack in c++', 'How can I implement a stack in c++?', '2021-01-03 14:21:55');
INSERT INTO public."question"(user_id, title, text, date) VALUES(34, 'a stack in python', 'How can I implement a stack in python?', '2020-06-22 08:48:09');
INSERT INTO public."question"(user_id, title, text, date) VALUES(37, 'a stack in javascript', 'How can I implement a stack in javascript?', '2021-02-02 21:44:54');
INSERT INTO public."question"(user_id, title, text, date) VALUES(3, 'a stack in java', 'How can I implement a stack in java?', '2020-10-14 03:01:18');
INSERT INTO public."question"(user_id, title, text, date) VALUES(35, 'a stack in swipl', 'How can I implement a stack in swipl?', '2021-01-07 02:27:17');
INSERT INTO public."question"(user_id, title, text, date) VALUES(26, 'a graph in c++', 'How can I implement a graph in c++?', '2021-05-25 11:39:57');
INSERT INTO public."question"(user_id, title, text, date) VALUES(24, 'a graph in python', 'How can I implement a graph in python?', '2021-02-15 21:40:25');
INSERT INTO public."question"(user_id, title, text, date) VALUES(13, 'a graph in javascript', 'How can I implement a graph in javascript?', '2021-02-06 17:18:03');
INSERT INTO public."question"(user_id, title, text, date) VALUES(22, 'a graph in java', 'How can I implement a graph in java?', '2021-04-26 13:30:20');
INSERT INTO public."question"(user_id, title, text, date) VALUES(38, 'a graph in swipl', 'How can I implement a graph in swipl?', '2021-04-25 05:00:41');
INSERT INTO public."question"(user_id, title, text, date) VALUES(39, 'a tree in c++', 'How can I implement a tree in c++?', '2021-04-05 12:54:13');
INSERT INTO public."question"(user_id, title, text, date) VALUES(28, 'a tree in python', 'How can I implement a tree in python?', '2021-01-28 01:51:13');
INSERT INTO public."question"(user_id, title, text, date) VALUES(47, 'a tree in javascript', 'How can I implement a tree in javascript?', '2021-01-14 21:27:09');
INSERT INTO public."question"(user_id, title, text, date) VALUES(14, 'a tree in java', 'How can I implement a tree in java?', '2021-01-15 13:11:48');
INSERT INTO public."question"(user_id, title, text, date) VALUES(51, 'a tree in swipl', 'How can I implement a tree in swipl?', '2021-05-19 05:36:29');
INSERT INTO public."question"(user_id, title, text, date) VALUES(28, 'a set in c++', 'How can I implement a set in c++?', '2021-03-17 08:45:04');
INSERT INTO public."question"(user_id, title, text, date) VALUES(14, 'a set in python', 'How can I implement a set in python?', '2021-01-20 12:08:54');
INSERT INTO public."question"(user_id, title, text, date) VALUES(46, 'a set in javascript', 'How can I implement a set in javascript?', '2021-02-25 18:18:46');
INSERT INTO public."question"(user_id, title, text, date) VALUES(40, 'a set in java', 'How can I implement a set in java?', '2021-01-21 23:49:19');
INSERT INTO public."question"(user_id, title, text, date) VALUES(31, 'a set in swipl', 'How can I implement a set in swipl?', '2021-04-19 07:41:36');
INSERT INTO public."question"(user_id, title, text, date) VALUES(14, 'a dictionary in c++', 'How can I implement a dictionary in c++?', '2020-10-06 12:35:18');
INSERT INTO public."question"(user_id, title, text, date) VALUES(48, 'a dictionary in python', 'How can I implement a dictionary in python?', '2021-01-19 01:11:53');
INSERT INTO public."question"(user_id, title, text, date) VALUES(3, 'a dictionary in javascript', 'How can I implement a dictionary in javascript?', '2021-01-02 20:41:58');
INSERT INTO public."question"(user_id, title, text, date) VALUES(9, 'a dictionary in java', 'How can I implement a dictionary in java?', '2021-04-16 17:48:47');
INSERT INTO public."question"(user_id, title, text, date) VALUES(22, 'a dictionary in swipl', 'How can I implement a dictionary in swipl?', '2021-04-19 00:37:34');
INSERT INTO public."question"(user_id, title, text, date) VALUES(24, 'a min heap in c++', 'How can I implement a min heap in c++?', '2021-03-20 17:30:52');
INSERT INTO public."question"(user_id, title, text, date) VALUES(24, 'a min heap in python', 'How can I implement a min heap in python?', '2021-03-28 23:58:10');
INSERT INTO public."question"(user_id, title, text, date) VALUES(11, 'a min heap in javascript', 'How can I implement a min heap in javascript?', '2021-02-16 05:46:52');
INSERT INTO public."question"(user_id, title, text, date) VALUES(21, 'a min heap in java', 'How can I implement a min heap in java?', '2021-03-09 06:47:04');
INSERT INTO public."question"(user_id, title, text, date) VALUES(37, 'a min heap in swipl', 'How can I implement a min heap in swipl?', '2021-04-26 17:27:27');
INSERT INTO public."question"(user_id, title, text, date) VALUES(25, 'a max heap in c++', 'How can I implement a max heap in c++?', '2021-02-14 04:20:23');
INSERT INTO public."question"(user_id, title, text, date) VALUES(13, 'a max heap in python', 'How can I implement a max heap in python?', '2021-04-16 05:33:14');
INSERT INTO public."question"(user_id, title, text, date) VALUES(27, 'a max heap in javascript', 'How can I implement a max heap in javascript?', '2021-05-28 20:52:17');
INSERT INTO public."question"(user_id, title, text, date) VALUES(41, 'a max heap in java', 'How can I implement a max heap in java?', '2021-01-16 16:31:23');
INSERT INTO public."question"(user_id, title, text, date) VALUES(34, 'a max heap in swipl', 'How can I implement a max heap in swipl?', '2021-01-12 03:35:37');
INSERT INTO public."question"(user_id, title, text, date) VALUES(18, 'center text in html', 'How can I center text with html?', '2021-02-18 05:41:13');
INSERT INTO public."question"(user_id, title, text, date) VALUES(18, 'center text in css', 'How can I center text with css?', '2021-03-20 23:29:25');
INSERT INTO public."question"(user_id, title, text, date) VALUES(32, 'center text in javascript', 'How can I center text with javascript?', '2020-11-15 10:37:38');
INSERT INTO public."question"(user_id, title, text, date) VALUES(32, 'center text in react', 'How can I center text with react?', '2021-02-26 03:50:24');
INSERT INTO public."question"(user_id, title, text, date) VALUES(18, 'center text in angular', 'How can I center text with angular?', '2021-03-19 14:32:03');
INSERT INTO public."question"(user_id, title, text, date) VALUES(23, 'change background color in html', 'How can I change background color with html?', '2020-06-24 15:05:27');
INSERT INTO public."question"(user_id, title, text, date) VALUES(23, 'change background color in css', 'How can I change background color with css?', '2020-07-03 07:51:47');
INSERT INTO public."question"(user_id, title, text, date) VALUES(31, 'change background color in javascript', 'How can I change background color with javascript?', '2020-10-19 21:10:31');
INSERT INTO public."question"(user_id, title, text, date) VALUES(26, 'change background color in react', 'How can I change background color with react?', '2020-11-27 10:01:22');
INSERT INTO public."question"(user_id, title, text, date) VALUES(32, 'change background color in angular', 'How can I change background color with angular?', '2020-04-11 11:46:21');
INSERT INTO public."question"(user_id, title, text, date) VALUES(47, 'create a form in html', 'How can I create a form with html?', '2020-03-04 05:55:10');
INSERT INTO public."question"(user_id, title, text, date) VALUES(29, 'create a form in css', 'How can I create a form with css?', '2021-03-13 06:30:28');
INSERT INTO public."question"(user_id, title, text, date) VALUES(40, 'create a form in javascript', 'How can I create a form with javascript?', '2020-06-24 15:38:02');
INSERT INTO public."question"(user_id, title, text, date) VALUES(33, 'create a form in react', 'How can I create a form with react?', '2020-10-17 19:40:24');
INSERT INTO public."question"(user_id, title, text, date) VALUES(8, 'create a form in angular', 'How can I create a form with angular?', '2021-03-28 01:31:35');
INSERT INTO public."question"(user_id, title, text, date) VALUES(12, 'add dark mode in html', 'How can I add dark mode with html?', '2021-04-20 20:40:19');
INSERT INTO public."question"(user_id, title, text, date) VALUES(48, 'add dark mode in css', 'How can I add dark mode with css?', '2020-03-15 01:50:12');
INSERT INTO public."question"(user_id, title, text, date) VALUES(31, 'add dark mode in javascript', 'How can I add dark mode with javascript?', '2021-05-05 05:47:39');
INSERT INTO public."question"(user_id, title, text, date) VALUES(7, 'add dark mode in react', 'How can I add dark mode with react?', '2021-04-20 10:11:40');
INSERT INTO public."question"(user_id, title, text, date) VALUES(14, 'add dark mode in angular', 'How can I add dark mode with angular?', '2021-02-04 01:16:15');
INSERT INTO public."question"(user_id, title, text, date) VALUES(50, 'add animation in html', 'How can I add animation with html?', '2021-05-17 23:43:03');
INSERT INTO public."question"(user_id, title, text, date) VALUES(7, 'add animation in css', 'How can I add animation with css?', '2021-03-20 06:35:32');
INSERT INTO public."question"(user_id, title, text, date) VALUES(47, 'add animation in javascript', 'How can I add animation with javascript?', '2021-02-16 09:30:25');
INSERT INTO public."question"(user_id, title, text, date) VALUES(23, 'add animation in react', 'How can I add animation with react?', '2020-12-04 12:11:39');
INSERT INTO public."question"(user_id, title, text, date) VALUES(29, 'add animation in angular', 'How can I add animation with angular?', '2021-01-10 18:10:30');
INSERT INTO public."question"(user_id, title, text, date) VALUES(34, 'change background in ubuntu', 'How can I change background in ubuntu?', '2020-11-26 06:47:17');
INSERT INTO public."question"(user_id, title, text, date) VALUES(18, 'change background in linux', 'How can I change background in linux?', '2021-04-24 19:38:33');
INSERT INTO public."question"(user_id, title, text, date) VALUES(9, 'change background in windows', 'How can I change background in windows?', '2021-01-23 23:08:29');
INSERT INTO public."question"(user_id, title, text, date) VALUES(28, 'install vscode in ubuntu', 'How can I install vscode in ubuntu?', '2020-02-08 19:21:12');
INSERT INTO public."question"(user_id, title, text, date) VALUES(13, 'install vscode in linux', 'How can I install vscode in linux?', '2021-03-04 10:38:18');
INSERT INTO public."question"(user_id, title, text, date) VALUES(49, 'install vscode in windows', 'How can I install vscode in windows?', '2021-05-02 21:51:35');
INSERT INTO public."question"(user_id, title, text, date) VALUES(51, 'delete a directory in ubuntu', 'How can I delete a directory in ubuntu?', '2020-04-14 01:13:48');
INSERT INTO public."question"(user_id, title, text, date) VALUES(28, 'delete a directory in linux', 'How can I delete a directory in linux?', '2021-02-16 01:55:46');
INSERT INTO public."question"(user_id, title, text, date) VALUES(24, 'delete a directory in windows', 'How can I delete a directory in windows?', '2021-03-25 15:34:57');
INSERT INTO public."question"(user_id, title, text, date) VALUES(50, 'rename a directory in ubuntu', 'How can I rename a directory in ubuntu?', '2021-01-16 22:17:53');
INSERT INTO public."question"(user_id, title, text, date) VALUES(35, 'rename a directory in linux', 'How can I rename a directory in linux?', '2021-02-06 13:20:51');
INSERT INTO public."question"(user_id, title, text, date) VALUES(4, 'rename a directory in windows', 'How can I rename a directory in windows?', '2021-03-28 23:17:53');
INSERT INTO public."question"(user_id, title, text, date) VALUES(9, 'download chrome in ubuntu', 'How can I download chrome in ubuntu?', '2021-03-12 13:07:40');
INSERT INTO public."question"(user_id, title, text, date) VALUES(38, 'download chrome in linux', 'How can I download chrome in linux?', '2021-05-26 03:43:12');
INSERT INTO public."question"(user_id, title, text, date) VALUES(31, 'download chrome in windows', 'How can I download chrome in windows?', '2021-01-21 04:44:05');
INSERT INTO public."question"(user_id, title, text, date) VALUES(50, 'keep a backup in ubuntu', 'How can I keep a backup in ubuntu?', '2020-11-11 02:37:28');
INSERT INTO public."question"(user_id, title, text, date) VALUES(34, 'keep a backup in linux', 'How can I keep a backup in linux?', '2020-10-01 05:39:46');
INSERT INTO public."question"(user_id, title, text, date) VALUES(22, 'keep a backup in windows', 'How can I keep a backup in windows?', '2021-01-13 08:13:36');
INSERT INTO public."question"(user_id, title, text, date) VALUES(11, 'switch language in ubuntu', 'How can I switch language in ubuntu?', '2021-03-18 05:26:43');
INSERT INTO public."question"(user_id, title, text, date) VALUES(23, 'switch language in linux', 'How can I switch language in linux?', '2021-02-07 19:41:49');
INSERT INTO public."question"(user_id, title, text, date) VALUES(44, 'switch language in windows', 'How can I switch language in windows?', '2021-04-27 20:18:15');
