INSERT INTO public."question"(user_id, title, text, date) VALUES(16, 'insert in sql', 'What is the fastest way to insert data in sql?', '2020-07-31 07:12:53');
INSERT INTO public."question"(user_id, title, text, date) VALUES(2, 'insert in postgresql', 'What is the fastest way to insert data in postgresql?', '2021-01-26 08:34:15');
INSERT INTO public."question"(user_id, title, text, date) VALUES(10, 'insert in mongodb', 'What is the fastest way to insert data in mongodb?', '2021-03-11 23:30:13');
INSERT INTO public."question"(user_id, title, text, date) VALUES(42, 'insert in relational databases', 'What is the fastest way to insert data in relational databases?', '2021-04-20 00:43:03');
INSERT INTO public."question"(user_id, title, text, date) VALUES(47, 'insert in non-relational databases', 'What is the fastest way to insert data in non-relational databases?', '2021-05-23 13:32:22');
INSERT INTO public."question"(user_id, title, text, date) VALUES(11, 'insert in Django', 'What is the fastest way to insert data in Django?', '2021-03-17 15:29:03');
INSERT INTO public."question"(user_id, title, text, date) VALUES(28, 'insert in Spring boot', 'What is the fastest way to insert data in Spring boot?', '2021-04-21 10:08:20');
INSERT INTO public."question"(user_id, title, text, date) VALUES(47, 'insert in Laravel', 'What is the fastest way to insert data in Laravel?', '2021-05-04 17:03:58');
INSERT INTO public."question"(user_id, title, text, date) VALUES(34, 'delete in sql', 'What is the fastest way to delete data in sql?', '2021-01-18 07:19:04');
INSERT INTO public."question"(user_id, title, text, date) VALUES(10, 'delete in postgresql', 'What is the fastest way to delete data in postgresql?', '2021-03-22 08:15:52');
INSERT INTO public."question"(user_id, title, text, date) VALUES(28, 'delete in mongodb', 'What is the fastest way to delete data in mongodb?', '2021-05-12 01:52:33');
INSERT INTO public."question"(user_id, title, text, date) VALUES(15, 'delete in relational databases', 'What is the fastest way to delete data in relational databases?', '2021-06-16 06:25:36');
INSERT INTO public."question"(user_id, title, text, date) VALUES(3, 'delete in non-relational databases', 'What is the fastest way to delete data in non-relational databases?', '2020-10-21 02:47:06');
INSERT INTO public."question"(user_id, title, text, date) VALUES(25, 'delete in Django', 'What is the fastest way to delete data in Django?', '2021-06-07 14:21:40');
INSERT INTO public."question"(user_id, title, text, date) VALUES(43, 'delete in Spring boot', 'What is the fastest way to delete data in Spring boot?', '2021-02-25 11:40:20');
INSERT INTO public."question"(user_id, title, text, date) VALUES(12, 'delete in Laravel', 'What is the fastest way to delete data in Laravel?', '2021-06-20 01:50:54');
INSERT INTO public."question"(user_id, title, text, date) VALUES(33, 'update in sql', 'What is the fastest way to update data in sql?', '2021-05-05 20:30:20');
INSERT INTO public."question"(user_id, title, text, date) VALUES(7, 'update in postgresql', 'What is the fastest way to update data in postgresql?', '2021-02-17 03:40:36');
INSERT INTO public."question"(user_id, title, text, date) VALUES(25, 'update in mongodb', 'What is the fastest way to update data in mongodb?', '2021-06-05 14:15:37');
INSERT INTO public."question"(user_id, title, text, date) VALUES(15, 'update in relational databases', 'What is the fastest way to update data in relational databases?', '2021-05-27 19:11:05');
INSERT INTO public."question"(user_id, title, text, date) VALUES(18, 'update in non-relational databases', 'What is the fastest way to update data in non-relational databases?', '2021-05-02 09:27:03');
INSERT INTO public."question"(user_id, title, text, date) VALUES(43, 'update in Django', 'What is the fastest way to update data in Django?', '2020-07-02 06:51:08');
INSERT INTO public."question"(user_id, title, text, date) VALUES(30, 'update in Spring boot', 'What is the fastest way to update data in Spring boot?', '2021-05-12 16:50:53');
INSERT INTO public."question"(user_id, title, text, date) VALUES(24, 'update in Laravel', 'What is the fastest way to update data in Laravel?', '2020-11-14 16:00:59');
INSERT INTO public."question"(user_id, title, text, date) VALUES(33, 'read in sql', 'What is the fastest way to read data in sql?', '2021-06-19 18:30:44');
INSERT INTO public."question"(user_id, title, text, date) VALUES(17, 'read in postgresql', 'What is the fastest way to read data in postgresql?', '2021-05-14 04:54:13');
INSERT INTO public."question"(user_id, title, text, date) VALUES(3, 'read in mongodb', 'What is the fastest way to read data in mongodb?', '2020-12-15 20:29:29');
INSERT INTO public."question"(user_id, title, text, date) VALUES(15, 'read in relational databases', 'What is the fastest way to read data in relational databases?', '2021-05-27 05:37:01');
INSERT INTO public."question"(user_id, title, text, date) VALUES(8, 'read in non-relational databases', 'What is the fastest way to read data in non-relational databases?', '2021-04-24 21:21:38');
INSERT INTO public."question"(user_id, title, text, date) VALUES(25, 'read in Django', 'What is the fastest way to read data in Django?', '2021-06-23 15:55:57');
INSERT INTO public."question"(user_id, title, text, date) VALUES(14, 'read in Spring boot', 'What is the fastest way to read data in Spring boot?', '2021-06-06 09:59:15');
INSERT INTO public."question"(user_id, title, text, date) VALUES(47, 'read in Laravel', 'What is the fastest way to read data in Laravel?', '2020-11-17 07:29:56');
INSERT INTO public."question"(user_id, title, text, date) VALUES(41, 'an array in c++', 'How can I implement an array in c++?', '2020-09-23 04:18:58');
INSERT INTO public."question"(user_id, title, text, date) VALUES(31, 'an array in Python', 'How can I implement an array in Python?', '2021-05-21 00:32:49');
INSERT INTO public."question"(user_id, title, text, date) VALUES(4, 'an array in javascript', 'How can I implement an array in javascript?', '2021-04-02 08:22:16');
INSERT INTO public."question"(user_id, title, text, date) VALUES(27, 'an array in java', 'How can I implement an array in java?', '2021-05-16 21:53:43');
INSERT INTO public."question"(user_id, title, text, date) VALUES(21, 'an array in swipl', 'How can I implement an array in swipl?', '2021-03-16 19:35:33');
INSERT INTO public."question"(user_id, title, text, date) VALUES(20, 'a linked list in c++', 'How can I implement a linked list in c++?', '2020-05-30 15:14:52');
INSERT INTO public."question"(user_id, title, text, date) VALUES(26, 'a linked list in Python', 'How can I implement a linked list in Python?', '2021-06-07 18:02:39');
INSERT INTO public."question"(user_id, title, text, date) VALUES(38, 'a linked list in javascript', 'How can I implement a linked list in javascript?', '2021-06-24 11:25:23');
INSERT INTO public."question"(user_id, title, text, date) VALUES(37, 'a linked list in java', 'How can I implement a linked list in java?', '2021-03-17 02:40:08');
INSERT INTO public."question"(user_id, title, text, date) VALUES(32, 'a linked list in swipl', 'How can I implement a linked list in swipl?', '2021-06-29 15:36:42');
INSERT INTO public."question"(user_id, title, text, date) VALUES(19, 'a queue in c++', 'How can I implement a queue in c++?', '2021-04-05 05:56:26');
INSERT INTO public."question"(user_id, title, text, date) VALUES(7, 'a queue in Python', 'How can I implement a queue in Python?', '2021-03-23 01:45:41');
INSERT INTO public."question"(user_id, title, text, date) VALUES(37, 'a queue in javascript', 'How can I implement a queue in javascript?', '2021-04-26 22:52:01');
INSERT INTO public."question"(user_id, title, text, date) VALUES(41, 'a queue in java', 'How can I implement a queue in java?', '2020-12-31 13:09:55');
INSERT INTO public."question"(user_id, title, text, date) VALUES(49, 'a queue in swipl', 'How can I implement a queue in swipl?', '2021-02-03 23:17:19');
INSERT INTO public."question"(user_id, title, text, date) VALUES(9, 'a priority queue in c++', 'How can I implement a priority queue in c++?', '2021-06-04 07:26:07');
INSERT INTO public."question"(user_id, title, text, date) VALUES(40, 'a priority queue in Python', 'How can I implement a priority queue in Python?', '2021-06-27 06:36:31');
INSERT INTO public."question"(user_id, title, text, date) VALUES(7, 'a priority queue in javascript', 'How can I implement a priority queue in javascript?', '2021-06-19 06:32:33');
INSERT INTO public."question"(user_id, title, text, date) VALUES(1, 'a priority queue in java', 'How can I implement a priority queue in java?', '2021-06-24 07:42:10');
INSERT INTO public."question"(user_id, title, text, date) VALUES(41, 'a priority queue in swipl', 'How can I implement a priority queue in swipl?', '2021-01-21 12:04:38');
INSERT INTO public."question"(user_id, title, text, date) VALUES(23, 'a stack in c++', 'How can I implement a stack in c++?', '2021-02-20 23:38:54');
INSERT INTO public."question"(user_id, title, text, date) VALUES(18, 'a stack in Python', 'How can I implement a stack in Python?', '2021-05-21 23:39:07');
INSERT INTO public."question"(user_id, title, text, date) VALUES(38, 'a stack in javascript', 'How can I implement a stack in javascript?', '2021-05-14 15:17:55');
INSERT INTO public."question"(user_id, title, text, date) VALUES(30, 'a stack in java', 'How can I implement a stack in java?', '2021-05-04 19:47:18');
INSERT INTO public."question"(user_id, title, text, date) VALUES(22, 'a stack in swipl', 'How can I implement a stack in swipl?', '2021-02-17 13:24:32');
INSERT INTO public."question"(user_id, title, text, date) VALUES(46, 'a graph in c++', 'How can I implement a graph in c++?', '2020-12-18 21:44:42');
INSERT INTO public."question"(user_id, title, text, date) VALUES(21, 'a graph in Python', 'How can I implement a graph in Python?', '2021-05-14 06:59:49');
INSERT INTO public."question"(user_id, title, text, date) VALUES(10, 'a graph in javascript', 'How can I implement a graph in javascript?', '2021-05-11 16:42:33');
INSERT INTO public."question"(user_id, title, text, date) VALUES(46, 'a graph in java', 'How can I implement a graph in java?', '2021-04-16 09:48:56');
INSERT INTO public."question"(user_id, title, text, date) VALUES(27, 'a graph in swipl', 'How can I implement a graph in swipl?', '2021-04-29 10:52:47');
INSERT INTO public."question"(user_id, title, text, date) VALUES(45, 'a tree in c++', 'How can I implement a tree in c++?', '2021-02-02 04:17:53');
INSERT INTO public."question"(user_id, title, text, date) VALUES(12, 'a tree in Python', 'How can I implement a tree in Python?', '2020-09-27 05:36:34');
INSERT INTO public."question"(user_id, title, text, date) VALUES(31, 'a tree in javascript', 'How can I implement a tree in javascript?', '2021-02-19 07:00:29');
INSERT INTO public."question"(user_id, title, text, date) VALUES(46, 'a tree in java', 'How can I implement a tree in java?', '2021-03-03 16:33:30');
INSERT INTO public."question"(user_id, title, text, date) VALUES(30, 'a tree in swipl', 'How can I implement a tree in swipl?', '2021-06-27 03:52:00');
INSERT INTO public."question"(user_id, title, text, date) VALUES(16, 'a set in c++', 'How can I implement a set in c++?', '2021-05-02 04:12:01');
INSERT INTO public."question"(user_id, title, text, date) VALUES(37, 'a set in Python', 'How can I implement a set in Python?', '2021-04-01 00:09:30');
INSERT INTO public."question"(user_id, title, text, date) VALUES(36, 'a set in javascript', 'How can I implement a set in javascript?', '2021-02-21 10:58:07');
INSERT INTO public."question"(user_id, title, text, date) VALUES(44, 'a set in java', 'How can I implement a set in java?', '2021-06-02 15:09:43');
INSERT INTO public."question"(user_id, title, text, date) VALUES(5, 'a set in swipl', 'How can I implement a set in swipl?', '2021-06-30 15:56:43');
INSERT INTO public."question"(user_id, title, text, date) VALUES(21, 'a dictionary in c++', 'How can I implement a dictionary in c++?', '2021-06-22 05:03:43');
INSERT INTO public."question"(user_id, title, text, date) VALUES(10, 'a dictionary in Python', 'How can I implement a dictionary in Python?', '2021-05-09 17:09:20');
INSERT INTO public."question"(user_id, title, text, date) VALUES(43, 'a dictionary in javascript', 'How can I implement a dictionary in javascript?', '2020-12-15 13:54:43');
INSERT INTO public."question"(user_id, title, text, date) VALUES(21, 'a dictionary in java', 'How can I implement a dictionary in java?', '2021-05-24 22:44:23');
INSERT INTO public."question"(user_id, title, text, date) VALUES(43, 'a dictionary in swipl', 'How can I implement a dictionary in swipl?', '2021-02-05 07:56:12');
INSERT INTO public."question"(user_id, title, text, date) VALUES(28, 'a min heap in c++', 'How can I implement a min heap in c++?', '2021-05-19 02:31:44');
INSERT INTO public."question"(user_id, title, text, date) VALUES(10, 'a min heap in Python', 'How can I implement a min heap in Python?', '2021-03-23 18:25:51');
INSERT INTO public."question"(user_id, title, text, date) VALUES(30, 'a min heap in javascript', 'How can I implement a min heap in javascript?', '2021-05-18 19:04:59');
INSERT INTO public."question"(user_id, title, text, date) VALUES(27, 'a min heap in java', 'How can I implement a min heap in java?', '2021-05-15 07:44:36');
INSERT INTO public."question"(user_id, title, text, date) VALUES(41, 'a min heap in swipl', 'How can I implement a min heap in swipl?', '2020-09-15 09:25:44');
INSERT INTO public."question"(user_id, title, text, date) VALUES(33, 'a max heap in c++', 'How can I implement a max heap in c++?', '2021-05-08 06:20:04');
INSERT INTO public."question"(user_id, title, text, date) VALUES(35, 'a max heap in Python', 'How can I implement a max heap in Python?', '2021-04-15 17:00:31');
INSERT INTO public."question"(user_id, title, text, date) VALUES(26, 'a max heap in javascript', 'How can I implement a max heap in javascript?', '2021-05-25 13:16:30');
INSERT INTO public."question"(user_id, title, text, date) VALUES(3, 'a max heap in java', 'How can I implement a max heap in java?', '2021-03-19 02:05:59');
INSERT INTO public."question"(user_id, title, text, date) VALUES(3, 'a max heap in swipl', 'How can I implement a max heap in swipl?', '2020-11-28 16:25:01');
INSERT INTO public."question"(user_id, title, text, date) VALUES(8, 'center text in html', 'How can I center text with html?', '2021-05-17 10:54:20');
INSERT INTO public."question"(user_id, title, text, date) VALUES(22, 'center text in css', 'How can I center text with css?', '2021-04-01 22:41:17');
INSERT INTO public."question"(user_id, title, text, date) VALUES(20, 'center text in javascript', 'How can I center text with javascript?', '2021-03-11 23:50:08');
INSERT INTO public."question"(user_id, title, text, date) VALUES(28, 'center text in react', 'How can I center text with react?', '2021-04-09 07:27:10');
INSERT INTO public."question"(user_id, title, text, date) VALUES(28, 'center text in angular', 'How can I center text with angular?', '2021-06-14 19:02:29');
INSERT INTO public."question"(user_id, title, text, date) VALUES(8, 'change background color in html', 'How can I change background color with html?', '2021-04-04 18:03:17');
INSERT INTO public."question"(user_id, title, text, date) VALUES(46, 'change background color in css', 'How can I change background color with css?', '2021-04-20 12:24:15');
INSERT INTO public."question"(user_id, title, text, date) VALUES(5, 'change background color in javascript', 'How can I change background color with javascript?', '2020-12-30 04:42:02');
INSERT INTO public."question"(user_id, title, text, date) VALUES(12, 'change background color in react', 'How can I change background color with react?', '2020-08-05 02:28:22');
INSERT INTO public."question"(user_id, title, text, date) VALUES(18, 'change background color in angular', 'How can I change background color with angular?', '2021-05-26 19:08:38');
INSERT INTO public."question"(user_id, title, text, date) VALUES(5, 'create a form in html', 'How can I create a form with html?', '2021-01-03 18:19:25');
INSERT INTO public."question"(user_id, title, text, date) VALUES(48, 'create a form in css', 'How can I create a form with css?', '2021-05-24 02:18:17');
INSERT INTO public."question"(user_id, title, text, date) VALUES(34, 'create a form in javascript', 'How can I create a form with javascript?', '2021-02-05 19:10:02');
INSERT INTO public."question"(user_id, title, text, date) VALUES(12, 'create a form in react', 'How can I create a form with react?', '2020-11-09 20:12:13');
INSERT INTO public."question"(user_id, title, text, date) VALUES(28, 'create a form in angular', 'How can I create a form with angular?', '2021-06-13 16:05:39');
INSERT INTO public."question"(user_id, title, text, date) VALUES(39, 'add dark mode in html', 'How can I add dark mode with html?', '2021-04-17 01:23:52');
INSERT INTO public."question"(user_id, title, text, date) VALUES(42, 'add dark mode in css', 'How can I add dark mode with css?', '2021-06-15 01:09:53');
INSERT INTO public."question"(user_id, title, text, date) VALUES(1, 'add dark mode in javascript', 'How can I add dark mode with javascript?', '2021-06-30 21:32:03');
INSERT INTO public."question"(user_id, title, text, date) VALUES(43, 'add dark mode in react', 'How can I add dark mode with react?', '2020-07-21 03:32:35');
INSERT INTO public."question"(user_id, title, text, date) VALUES(40, 'add dark mode in angular', 'How can I add dark mode with angular?', '2021-05-30 11:30:20');
INSERT INTO public."question"(user_id, title, text, date) VALUES(10, 'add animation in html', 'How can I add animation with html?', '2021-06-07 02:08:08');
INSERT INTO public."question"(user_id, title, text, date) VALUES(9, 'add animation in css', 'How can I add animation with css?', '2021-02-28 09:07:33');
INSERT INTO public."question"(user_id, title, text, date) VALUES(47, 'add animation in javascript', 'How can I add animation with javascript?', '2021-05-12 05:23:15');
INSERT INTO public."question"(user_id, title, text, date) VALUES(35, 'add animation in react', 'How can I add animation with react?', '2021-06-22 19:56:32');
INSERT INTO public."question"(user_id, title, text, date) VALUES(20, 'add animation in angular', 'How can I add animation with angular?', '2020-10-03 22:33:25');
INSERT INTO public."question"(user_id, title, text, date) VALUES(44, 'change background in ubuntu', 'How can I change background in ubuntu?', '2021-05-18 18:18:47');
INSERT INTO public."question"(user_id, title, text, date) VALUES(10, 'change background in linux', 'How can I change background in linux?', '2021-05-01 23:59:20');
INSERT INTO public."question"(user_id, title, text, date) VALUES(9, 'change background in windows', 'How can I change background in windows?', '2021-02-05 22:32:13');
INSERT INTO public."question"(user_id, title, text, date) VALUES(28, 'install vscode in ubuntu', 'How can I install vscode in ubuntu?', '2021-05-19 08:13:08');
INSERT INTO public."question"(user_id, title, text, date) VALUES(45, 'install vscode in linux', 'How can I install vscode in linux?', '2021-04-19 12:49:07');
INSERT INTO public."question"(user_id, title, text, date) VALUES(19, 'install vscode in windows', 'How can I install vscode in windows?', '2021-06-29 07:37:55');
INSERT INTO public."question"(user_id, title, text, date) VALUES(30, 'delete a directory in ubuntu', 'How can I delete a directory in ubuntu?', '2021-06-17 09:57:15');
INSERT INTO public."question"(user_id, title, text, date) VALUES(10, 'delete a directory in linux', 'How can I delete a directory in linux?', '2021-04-24 12:32:41');
INSERT INTO public."question"(user_id, title, text, date) VALUES(14, 'delete a directory in windows', 'How can I delete a directory in windows?', '2021-05-10 04:14:46');
INSERT INTO public."question"(user_id, title, text, date) VALUES(31, 'rename a directory in ubuntu', 'How can I rename a directory in ubuntu?', '2021-01-30 08:12:25');
INSERT INTO public."question"(user_id, title, text, date) VALUES(32, 'rename a directory in linux', 'How can I rename a directory in linux?', '2021-06-11 12:13:37');
INSERT INTO public."question"(user_id, title, text, date) VALUES(3, 'rename a directory in windows', 'How can I rename a directory in windows?', '2020-09-01 00:06:23');
INSERT INTO public."question"(user_id, title, text, date) VALUES(16, 'download chrome in ubuntu', 'How can I download chrome in ubuntu?', '2021-02-25 15:50:09');
INSERT INTO public."question"(user_id, title, text, date) VALUES(43, 'download chrome in linux', 'How can I download chrome in linux?', '2021-01-31 09:35:58');
INSERT INTO public."question"(user_id, title, text, date) VALUES(11, 'download chrome in windows', 'How can I download chrome in windows?', '2021-01-29 08:15:48');
INSERT INTO public."question"(user_id, title, text, date) VALUES(27, 'keep a backup in ubuntu', 'How can I keep a backup in ubuntu?', '2021-04-15 07:50:42');
INSERT INTO public."question"(user_id, title, text, date) VALUES(35, 'keep a backup in linux', 'How can I keep a backup in linux?', '2021-06-04 04:47:25');
INSERT INTO public."question"(user_id, title, text, date) VALUES(9, 'keep a backup in windows', 'How can I keep a backup in windows?', '2021-05-31 00:41:45');
INSERT INTO public."question"(user_id, title, text, date) VALUES(28, 'switch language in ubuntu', 'How can I switch language in ubuntu?', '2021-06-24 12:10:07');
INSERT INTO public."question"(user_id, title, text, date) VALUES(9, 'switch language in linux', 'How can I switch language in linux?', '2021-06-23 01:02:54');
INSERT INTO public."question"(user_id, title, text, date) VALUES(40, 'switch language in windows', 'How can I switch language in windows?', '2021-01-28 23:51:35');
