INSERT INTO public."keyword"(name) VALUES('Django');
INSERT INTO public."keyword"(name) VALUES('Spring boot');
INSERT INTO public."keyword"(name) VALUES('Express js');
INSERT INTO public."keyword"(name) VALUES('Node js');
INSERT INTO public."keyword"(name) VALUES('Laravel');
INSERT INTO public."keyword"(name) VALUES('Python');
INSERT INTO public."keyword"(name) VALUES('c++');
INSERT INTO public."keyword"(name) VALUES('algorithms');
INSERT INTO public."keyword"(name) VALUES('data structures');
INSERT INTO public."keyword"(name) VALUES('sql');
INSERT INTO public."keyword"(name) VALUES('databases');
INSERT INTO public."keyword"(name) VALUES('postgres');
INSERT INTO public."keyword"(name) VALUES('heroku');
INSERT INTO public."keyword"(name) VALUES('vscode');
INSERT INTO public."keyword"(name) VALUES('webstormweb developing');
INSERT INTO public."keyword"(name) VALUES('html');
INSERT INTO public."keyword"(name) VALUES('css');
INSERT INTO public."keyword"(name) VALUES('vanilla js');
INSERT INTO public."keyword"(name) VALUES('react');
INSERT INTO public."keyword"(name) VALUES('angular');
INSERT INTO public."keyword"(name) VALUES('react-native');
INSERT INTO public."keyword"(name) VALUES('vue');
INSERT INTO public."keyword"(name) VALUES('flutter');
INSERT INTO public."keyword"(name) VALUES('selenium');
INSERT INTO public."keyword"(name) VALUES('ubuntu');
INSERT INTO public."keyword"(name) VALUES('linux');
INSERT INTO public."keyword"(name) VALUES('windows');